### ISSUE TITLE
运行generate.py没有反应

### ISSUE THREAD

**Issue by Data2Me** [Facico/Chinese-Vicuna#101]
我的执行命令：CUDA_VISIBLE_DEVICES=1 python3 /mnt/cpfs/guanyutao/Chinese-Vicuna/generate.py \
    --model_path /mnt/cpfs/guanyutao/model_checkpoint/llama-7b-hf \
    --lora_path /mnt/cpfs/guanyutao/model_checkpoint/Vicuna_finetune/checkpoint-10000 \
    --use_local 1 \
    --use_typewriter 1

执行运行到这个地方就没有反应了，也没有报错，就是卡在这里。我理解gradio应该输出一个网址。
![image](https://user-images.githubusercontent.com/59723064/233817207-41399ebf-a670-4da8-900f-22c4ed16867c.png)

**Comment by Facico** [comment]
可以根据我们提供的相关配置修改一下版本依赖，https://github.com/Facico/Chinese-Vicuna/blob/master/docs/problems.md
需要注意的是gradio、transformers、peft这几个配置（transformers和peft由于是直接从github拉去的，他们现在已经更新了好多版本所以可能会存在问题）
可以使用
https://github.com/huggingface/transformers@ff20f9cf3615a8638023bc82925573cb9d0f3560（或者transformers直接使用4.28.0）
和
git+https://github.com/huggingface/peft@e536616888d51b453ed354a6f1e243fecb02ea08
