### ISSUE TITLE
Chinese-Vicuna-medical 可以直接使用吗？如何直接使用

### ISSUE THREAD

**Issue by rdaim** [Facico/Chinese-Vicuna#105]
Chinese-Vicuna-medical 可以直接使用吗？如何直接使用

**Comment by Facico** [comment]
和其他lora模型一样加载就行了

**Comment by rdaim** [comment]
下载 7B 模型时，总是报错，md5sum: stat 'consolidated.00.pth': No such file or directory

**Comment by bash99** [comment]
我加载了测试后，效果没有 [performance-medical.md](https://github.com/Facico/Chinese-Vicuna/blob/master/docs/performance-medical.md) 那样啊？

改了chat.py，debug最后的输入和输出(tokenizer之前)：
input
```
The following is a conversation between an AI assistant called Assistant and a human user called User.

### Instruction:
扮演一个专业的医生并回答病人的问题。
病人：扁桃体炎引起的发烧该怎么治疗

### Response:
```

output（去掉input重复的部分）
```
1.这种情况建��你可以口服抗��片，��适量多����外擦止��痒
2.对于扁桃体炎��症是由于感染或其他原因引起的局部炎��症，主要表现为红肿、皮疹、瘙��、水肿等����性皮炎形式，常在夏��年初到秋��之间持续而不消除，如果长期不及时治��则会导致皮��痕变成大��������痣�������������������������������������������������������������
```

另外，如果在vicuna 13b 1.1上训练，是不是中文效果也会可以？

**Comment by Facico** [comment]
你这个乱码问题可能在加载任何中文的lora模型都会有，可能有以下原因：
1、tokenizer和sentencepiece版本的问题，这个问题可以参考我们的提供的[配置](https://github.com/Facico/Chinese-Vicuna/blob/master/docs/problems.md)
2、显卡和8bit不兼容的问题。比如V100就不太兼容（可以到仓库找相关的V100的问题）（这个问题可以用纯cpu推理的方式来排查） 解决方法是推理的时候把8bit相关的去掉改成fp16，相关https://github.com/Facico/Chinese-Vicuna/issues/39有说明
