### ISSUE TITLE
运行generate.sh后一直报model为NoneType

### ISSUE THREAD

**Issue by JupyterChu** [Facico/Chinese-Vicuna#111]
操作系统： CentOS Linux 7
GPU: 3090，一张
python版本：3.8.16
库的版本和requirements.txt中一致
llama-7b-hf数据提前下好了
cuda版本：11.4
nvcc --version：
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Aug_15_21:14:11_PDT_2021
Cuda compilation tools, release 11.4, V11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0`

报错信息：
CUDA SETUP: CUDA runtime path found: ...................../.conda/envs/py38/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 118
CUDA SETUP: Loading binary ...................../python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...
Namespace(lora_path='Chinese-Vicuna/Chinese-Vicuna-lora-7b-belle-and-guanaco', model_path='decapoda-research/llama-7b-hf', use_local=0, use_typewriter=1)
Chinese-Vicuna/Chinese-Vicuna-lora-7b-belle-and-guanaco/adapter_model.bin

Loading checkpoint shards:   0%|          | 0/33 [00:00<?, ?it/s]
Loading checkpoint shards:   3%|▎         | 1/33 [00:02<01:20,  2.51s/it]
Loading checkpoint shards:   6%|▌         | 2/33 [00:02<00:40,  1.32s/it]
Loading checkpoint shards:   9%|▉         | 3/33 [00:03<00:28,  1.06it/s]
Loading checkpoint shards:  12%|█▏        | 4/33 [00:03<00:22,  1.32it/s]
Loading checkpoint shards:  15%|█▌        | 5/33 [00:04<00:18,  1.52it/s]
Loading checkpoint shards:  18%|█▊        | 6/33 [00:04<00:16,  1.67it/s]
Loading checkpoint shards:  21%|██        | 7/33 [00:05<00:14,  1.79it/s]
Loading checkpoint shards:  24%|██▍       | 8/33 [00:05<00:13,  1.87it/s]
Loading checkpoint shards:  27%|██▋       | 9/33 [00:06<00:12,  1.94it/s]
Loading checkpoint shards:  30%|███       | 10/33 [00:06<00:11,  1.98it/s]
Loading checkpoint shards:  33%|███▎      | 11/33 [00:07<00:10,  2.02it/s]
Loading checkpoint shards:  36%|███▋      | 12/33 [00:07<00:10,  2.03it/s]
Loading checkpoint shards:  39%|███▉      | 13/33 [00:08<00:09,  2.04it/s]
Loading checkpoint shards:  42%|████▏     | 14/33 [00:08<00:09,  2.06it/s]
Loading checkpoint shards:  45%|████▌     | 15/33 [00:09<00:08,  2.06it/s]
Loading checkpoint shards:  48%|████▊     | 16/33 [00:09<00:08,  2.07it/s]
Loading checkpoint shards:  52%|█████▏    | 17/33 [00:10<00:07,  2.07it/s]
Loading checkpoint shards:  55%|█████▍    | 18/33 [00:10<00:07,  2.08it/s]
Loading checkpoint shards:  58%|█████▊    | 19/33 [00:11<00:06,  2.08it/s]
Loading checkpoint shards:  61%|██████    | 20/33 [00:11<00:06,  2.09it/s]
Loading checkpoint shards:  64%|██████▎   | 21/33 [00:12<00:05,  2.09it/s]
Loading checkpoint shards:  67%|██████▋   | 22/33 [00:12<00:05,  2.09it/s]
Loading checkpoint shards:  70%|██████▉   | 23/33 [00:13<00:04,  2.10it/s]
Loading checkpoint shards:  73%|███████▎  | 24/33 [00:13<00:04,  2.09it/s]
Loading checkpoint shards:  76%|███████▌  | 25/33 [00:14<00:03,  2.08it/s]
Loading checkpoint shards:  79%|███████▉  | 26/33 [00:14<00:03,  2.08it/s]
Loading checkpoint shards:  82%|████████▏ | 27/33 [00:14<00:02,  2.09it/s]
Loading checkpoint shards:  85%|████████▍ | 28/33 [00:15<00:02,  2.09it/s]
Loading checkpoint shards:  88%|████████▊ | 29/33 [00:15<00:01,  2.09it/s]
Loading checkpoint shards:  91%|█████████ | 30/33 [00:16<00:01,  2.09it/s]
Loading checkpoint shards:  94%|█████████▍| 31/33 [00:16<00:00,  2.10it/s]
Loading checkpoint shards:  97%|█████████▋| 32/33 [00:17<00:00,  2.09it/s]
Loading checkpoint shards: 100%|██████████| 33/33 [00:17<00:00,  2.05it/s]
Loading checkpoint shards: 100%|██████████| 33/33 [00:17<00:00,  1.84it/s]

Downloading (…)/adapter_config.json:   0%|          | 0.00/370 [00:00<?, ?B/s]
Downloading (…)/adapter_config.json: 100%|██████████| 370/370 [00:00<00:00, 110kB/s]

Downloading adapter_model.bin:   0%|          | 0.00/16.8M [00:00<?, ?B/s]
Downloading adapter_model.bin:  62%|██████▏   | 10.5M/16.8M [00:02<00:01, 4.31MB/s]
Downloading adapter_model.bin: 100%|██████████| 16.8M/16.8M [00:03<00:00, 4.52MB/s]
Downloading adapter_model.bin: 100%|██████████| 16.8M/16.8M [00:03<00:00, 4.47MB/s]
Traceback (most recent call last):
  File "generate.py", line 110, in <module>
    model.eval()
AttributeError: 'NoneType' object has no attribute 'eval'

求助，谢谢！

**Comment by Facico** [comment]
还是peft版本的问题，见这个[issue](https://github.com/Facico/Chinese-Vicuna/issues/51)
（其实类似的问题把报错信息在项目中搜一下说不定就有解决方案了）

**Comment by BiheZhu** [comment]
> 

好的，谢谢！我试试
