### ISSUE TITLE
纯CPP 推理，make chat 失败 

### ISSUE THREAD

**Issue by shikeno** [Facico/Chinese-Vicuna#114]
我根据文档CPP 推理的文档（https://github.com/Facico/Chinese-Vicuna/blob/master/tools/readme_zh.md）， 在运行make chat  的时候，发生了如下的错误。

g++     chat.cpp   -o chat
/tmp/cc48l8G9.o: In function `llama_model_load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, llama_model&, gpt_vocab&, int)':
chat.cpp:(.text+0x629): undefined reference to `ggml_type_sizef'
chat.cpp:(.text+0x6c9): undefined reference to `ggml_type_sizef'
chat.cpp:(.text+0x775): undefined reference to `ggml_type_sizef'
chat.cpp:(.text+0x825): undefined reference to `ggml_type_sizef'
chat.cpp:(.text+0x8e9): undefined reference to `ggml_type_sizef'
/tmp/cc48l8G9.o:chat.cpp:(.text+0x9ad): more undefined references to `ggml_type_sizef' follow
/tmp/cc48l8G9.o: In function `llama_model_load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, llama_model&, gpt_vocab&, int)':
chat.cpp:(.text+0x10d4): undefined reference to `ggml_init'
chat.cpp:(.text+0x11a9): undefined reference to `ggml_new_tensor_2d'
chat.cpp:(.text+0x11d4): undefined reference to `ggml_new_tensor_1d'
chat.cpp:(.text+0x1206): undefined reference to `ggml_new_tensor_2d'
chat.cpp:(.text+0x13d4): undefined reference to `ggml_new_tensor_1d'
chat.cpp:(.text+0x1405): undefined reference to `ggml_new_tensor_2d'
chat.cpp:(.text+0x1437): undefined reference to `ggml_new_tensor_2d'
chat.cpp:(.text+0x1469): undefined reference to `ggml_new_tensor_2d'
chat.cpp:(.text+0x149b): undefined reference to `ggml_new_tensor_2d'
chat.cpp:(.text+0x14c6): undefined reference to `ggml_new_tensor_1d'
chat.cpp:(.text+0x14f8): undefined reference to `ggml_new_tensor_2d'
chat.cpp:(.text+0x152a): undefined reference to `ggml_new_tensor_2d'
chat.cpp:(.text+0x155c): undefined reference to `ggml_new_tensor_2d'
chat.cpp:(.text+0x1bf9): undefined reference to `ggml_new_tensor_1d'
chat.cpp:(.text+0x1c24): undefined reference to `ggml_new_tensor_1d'
chat.cpp:(.text+0x1c45): undefined reference to `ggml_nbytes'
chat.cpp:(.text+0x1c5b): undefined reference to `ggml_nbytes'
chat.cpp:(.text+0x2333): undefined reference to `ggml_nelements'
chat.cpp:(.text+0x2396): undefined reference to `ggml_nelements'
chat.cpp:(.text+0x2643): undefined reference to `ggml_type_size'
chat.cpp:(.text+0x2659): undefined reference to `ggml_type_size'
chat.cpp:(.text+0x266f): undefined reference to `ggml_type_size'
chat.cpp:(.text+0x26aa): undefined reference to `ggml_type_size'
chat.cpp:(.text+0x274c): undefined reference to `ggml_blck_size'
chat.cpp:(.text+0x276c): undefined reference to `ggml_nbytes'
chat.cpp:(.text+0x2798): undefined reference to `ggml_nbytes'
chat.cpp:(.text+0x27fc): undefined reference to `ggml_nbytes'
chat.cpp:(.text+0x2830): undefined reference to `ggml_nbytes'
chat.cpp:(.text+0x2859): undefined reference to `ggml_nbytes'
chat.cpp:(.text+0x2888): undefined reference to `ggml_blck_size'
chat.cpp:(.text+0x28a8): undefined reference to `ggml_nbytes'
chat.cpp:(.text+0x28ef): undefined reference to `ggml_nbytes'
chat.cpp:(.text+0x2986): undefined reference to `ggml_blck_size'
chat.cpp:(.text+0x29a1): undefined reference to `ggml_type_size'
chat.cpp:(.text+0x2a2f): undefined reference to `ggml_blck_size'
chat.cpp:(.text+0x2a4a): undefined reference to `ggml_type_size'
chat.cpp:(.text+0x2ade): undefined reference to `ggml_blck_size'
chat.cpp:(.text+0x2af9): undefined reference to `ggml_type_size'
chat.cpp:(.text+0x2b90): undefined reference to `ggml_nbytes'
/tmp/cc48l8G9.o: In function `llama_eval(llama_model const&, int, int, std::vector<int, std::allocator<int> > const&, std::vector<float, std::allocator<float> >&, unsigned long&)':
chat.cpp:(.text+0x33a2): undefined reference to `ggml_init'
chat.cpp:(.text+0x33e8): undefined reference to `ggml_new_tensor_1d'
chat.cpp:(.text+0x3407): undefined reference to `ggml_element_size'
chat.cpp:(.text+0x345d): undefined reference to `ggml_get_rows'
chat.cpp:(.text+0x34a7): undefined reference to `ggml_rms_norm'
chat.cpp:(.text+0x34e8): undefined reference to `ggml_repeat'
chat.cpp:(.text+0x3504): undefined reference to `ggml_mul'
chat.cpp:(.text+0x3546): undefined reference to `ggml_mul_mat'
chat.cpp:(.text+0x3588): undefined reference to `ggml_mul_mat'
chat.cpp:(.text+0x35ca): undefined reference to `ggml_mul_mat'
chat.cpp:(.text+0x35f1): undefined reference to `ggml_element_size'
chat.cpp:(.text+0x3649): undefined reference to `ggml_view_1d'
chat.cpp:(.text+0x3663): undefined reference to `ggml_element_size'
chat.cpp:(.text+0x36bb): undefined reference to `ggml_view_1d'
chat.cpp:(.text+0x36e2): undefined reference to `ggml_cpy'
chat.cpp:(.text+0x36f7): undefined reference to `ggml_build_forward_expand'
chat.cpp:(.text+0x3717): undefined reference to `ggml_cpy'
chat.cpp:(.text+0x372c): undefined reference to `ggml_build_forward_expand'
chat.cpp:(.text+0x3762): undefined reference to `ggml_new_tensor_3d'
chat.cpp:(.text+0x377e): undefined reference to `ggml_cpy'
chat.cpp:(.text+0x37a2): undefined reference to `ggml_rope'
chat.cpp:(.text+0x37ca): undefined reference to `ggml_permute'
chat.cpp:(.text+0x3814): undefined reference to `ggml_element_size'
chat.cpp:(.text+0x385b): undefined reference to `ggml_view_1d'
chat.cpp:(.text+0x387b): undefined reference to `ggml_reshape_3d'
chat.cpp:(.text+0x389f): undefined reference to `ggml_rope'
chat.cpp:(.text+0x38c7): undefined reference to `ggml_permute'
chat.cpp:(.text+0x38ee): undefined reference to `ggml_mul_mat'
chat.cpp:(.text+0x3935): undefined reference to `ggml_new_f32'
chat.cpp:(.text+0x3951): undefined reference to `ggml_scale'
chat.cpp:(.text+0x3977): undefined reference to `ggml_diag_mask_inf'
chat.cpp:(.text+0x3997): undefined reference to `ggml_soft_max'
chat.cpp:(.text+0x39e1): undefined reference to `ggml_element_size'
chat.cpp:(.text+0x3a28): undefined reference to `ggml_view_1d'
chat.cpp:(.text+0x3a48): undefined reference to `ggml_reshape_3d'
chat.cpp:(.text+0x3a70): undefined reference to `ggml_permute'
chat.cpp:(.text+0x3a97): undefined reference to `ggml_mul_mat'
chat.cpp:(.text+0x3aca): undefined reference to `ggml_permute'
chat.cpp:(.text+0x3af1): undefined reference to `ggml_new_tensor_2d'
chat.cpp:(.text+0x3b0d): undefined reference to `ggml_cpy'
chat.cpp:(.text+0x3b4f): undefined reference to `ggml_mul_mat'
chat.cpp:(.text+0x3b76): undefined reference to `ggml_add'
chat.cpp:(.text+0x3b96): undefined reference to `ggml_rms_norm'
chat.cpp:(.text+0x3bd8): undefined reference to `ggml_repeat'
chat.cpp:(.text+0x3bf4): undefined reference to `ggml_mul'
chat.cpp:(.text+0x3c36): undefined reference to `ggml_mul_mat'
chat.cpp:(.text+0x3c78): undefined reference to `ggml_mul_mat'
chat.cpp:(.text+0x3c98): undefined reference to `ggml_silu'
chat.cpp:(.text+0x3cbf): undefined reference to `ggml_mul'
chat.cpp:(.text+0x3d01): undefined reference to `ggml_mul_mat'
chat.cpp:(.text+0x3d28): undefined reference to `ggml_add'
chat.cpp:(.text+0x3d62): undefined reference to `ggml_rms_norm'
chat.cpp:(.text+0x3d8d): undefined reference to `ggml_repeat'
chat.cpp:(.text+0x3da9): undefined reference to `ggml_mul'
chat.cpp:(.text+0x3dd4): undefined reference to `ggml_mul_mat'
chat.cpp:(.text+0x3df4): undefined reference to `ggml_build_forward_expand'
chat.cpp:(.text+0x3e0d): undefined reference to `ggml_graph_compute'
chat.cpp:(.text+0x3e47): undefined reference to `ggml_get_data'
chat.cpp:(.text+0x3e9f): undefined reference to `ggml_used_mem'
chat.cpp:(.text+0x3ed2): undefined reference to `ggml_free'
/tmp/cc48l8G9.o: In function `llama_print_system_info()':
chat.cpp:(.text+0x3fb4): undefined reference to `ggml_cpu_has_avx'
chat.cpp:(.text+0x402b): undefined reference to `ggml_cpu_has_avx2'
chat.cpp:(.text+0x40a2): undefined reference to `ggml_cpu_has_avx512'
chat.cpp:(.text+0x4119): undefined reference to `ggml_cpu_has_fma'
chat.cpp:(.text+0x4190): undefined reference to `ggml_cpu_has_neon'
chat.cpp:(.text+0x4207): undefined reference to `ggml_cpu_has_arm_fma'
chat.cpp:(.text+0x427e): undefined reference to `ggml_cpu_has_f16c'
chat.cpp:(.text+0x42f5): undefined reference to `ggml_cpu_has_fp16_va'
chat.cpp:(.text+0x436c): undefined reference to `ggml_cpu_has_wasm_simd'
chat.cpp:(.text+0x43e3): undefined reference to `ggml_cpu_has_blas'
chat.cpp:(.text+0x445a): undefined reference to `ggml_cpu_has_sse3'
chat.cpp:(.text+0x44d1): undefined reference to `ggml_cpu_has_vsx'
/tmp/cc48l8G9.o: In function `main':
chat.cpp:(.text+0x4874): undefined reference to `ggml_time_init'
chat.cpp:(.text+0x4879): undefined reference to `ggml_time_us'
chat.cpp:(.text+0x48ad): undefined reference to `gpt_params_parse(int, char**, gpt_params&)'
chat.cpp:(.text+0x4945): undefined reference to `ggml_time_us'
chat.cpp:(.text+0x49c0): undefined reference to `ggml_time_us'
chat.cpp:(.text+0x4a9d): undefined reference to `llama_tokenize(gpt_vocab const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
chat.cpp:(.text+0x4b07): undefined reference to `llama_tokenize(gpt_vocab const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
chat.cpp:(.text+0x4b71): undefined reference to `llama_tokenize(gpt_vocab const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
chat.cpp:(.text+0x4c42): undefined reference to `llama_tokenize(gpt_vocab const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
chat.cpp:(.text+0x506a): undefined reference to `ggml_time_us'
chat.cpp:(.text+0x50db): undefined reference to `ggml_time_us'
chat.cpp:(.text+0x51b5): undefined reference to `ggml_time_us'
chat.cpp:(.text+0x526c): undefined reference to `llama_sample_top_p_top_k(gpt_vocab const&, float const*, std::vector<int, std::allocator<int> >&, double, int, double, double, std::mersenne_twister_engine<unsigned long, 32ul, 624ul, 397ul, 31ul, 2567483615ul, 11ul, 4294967295ul, 7ul, 2636928640ul, 15ul, 4022730752ul, 18ul, 1812433253ul>&)'
chat.cpp:(.text+0x52d8): undefined reference to `ggml_time_us'
chat.cpp:(.text+0x579b): undefined reference to `llama_tokenize(gpt_vocab const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
chat.cpp:(.text+0x5965): undefined reference to `ggml_time_us'
chat.cpp:(.text+0x5ad0): undefined reference to `ggml_free'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'chat' failed
make: *** [chat] Error 1

环境：GPU  Tesla V100
 Mem 16GB
CPU 2 Cores
RAM 16GB
Disk 100GB

**Comment by Facico** [comment]
参考一下这个[issue](https://github.com/Facico/Chinese-Vicuna/issues/57)

**Comment by LZY-the-boys** [comment]
你先`cmake .`再`make chat`, 或者尝试用`make -f Makefile.ref `

**Comment by shikeno** [comment]
> 你先`cmake .`再`make chat`, 或者尝试用`make -f Makefile.ref `

感谢，解决了
