### ISSUE TITLE
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.

### ISSUE THREAD

**Issue by dizhenx** [Facico/Chinese-Vicuna#117]
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'. 
The class this function is called from is 'LlamaTokenizer'.
运行generate.sh的时候出现这个问题，不影响运行，但是可能会影响内容生成？怎么解决？

**Comment by Facico** [comment]
不用解决，我们直接调用的LlamaTokenizer不会有问题，如果用AutoTokenizer才会报错
