### ISSUE TITLE
这是什么情况，后面的回答都是回答的第一个问题？

### ISSUE THREAD

**Issue by lichao4Java** [Facico/Chinese-Vicuna#119]
![image](https://user-images.githubusercontent.com/13230226/234810761-821b2020-a3b9-4854-88de-b80398929997.png)

![image](https://user-images.githubusercontent.com/13230226/234810824-c462e0c7-1cb3-4811-ba7d-7b333b3f7632.png)

请问这是什么问题，后面的回答都是回答的第一个问题。？

是什么不对吗？

使用 interaction.sh 或者 chat.sh 都有这个问题。

**Comment by lichao4Java** [comment]
这是使用chat.sh。

prompt type=0

![image](https://user-images.githubusercontent.com/13230226/234814861-3d52ea93-9489-4a39-805f-a1fcd817421a.png)


这是prompt type=1

![image](https://user-images.githubusercontent.com/13230226/234815969-d3d7d2bb-1c31-40b5-b312-484bbed5ca62.png)

**Comment by Facico** [comment]
你用的是我们医疗问答的checkpoint吗，我们医疗问答还没适配多轮对话性的代码（global instruction）不一样
