### ISSUE TITLE
if it is possible to fine tune your model 

### ISSUE THREAD

**Issue by TY-hue123** [Facico/Chinese-Vicuna#128]
i tried to change the model's path as MODEL_PATH="Facico/Chinese-Vicuna-lora-7b-3epoch-belle-and-guanaco", but it can't find the model: 

https://github.com/Facico/Chinese-Vicuna/blob/master/finetune.sh#L8

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/132165516/235520086-f1805fdf-331f-4080-8e35-193eae1d1c57.png">

**Comment by SHITIANYU-hue** [comment]
I tried to use the pre-trained model (https://huggingface.co/Chinese-Vicuna/Chinese-Vicuna-lora-7b-belle-and-guanaco） to fine-tune on my own dataset but it cannot learn a good talking behavior: 

![image](https://user-images.githubusercontent.com/38762389/235802812-cde6319f-f643-4101-b165-0bee7e7d00c1.png)

**Comment by Facico** [comment]
@TY-hue123 Maybe it's a problem with your network? You can try downloading the model file and loading it offline。

**Comment by Facico** [comment]
@SHITIANYU-hue You can refer to this issue(https://github.com/Facico/Chinese-Vicuna/issues/121#issuecomment-1534012359)
Check your GPU and tokenizer. You can try using pure cpu inference to see whether you can produce normal results
