### ISSUE TITLE
流式输出结果和最终结果长度/内容相差较大

### ISSUE THREAD

**Issue by Aiemu** [Facico/Chinese-Vicuna#130]
在README的demo中流式输出结果（各个beam的输出）如下：
![](https://p.ipic.vip/k4tp9n.png)

最终呈现的结果如下：
![](https://p.ipic.vip/ppyo8e.png)

两者在长度和内容上都存在较大的差距，在本地使用时也存在这样的问题，请问应该如何解决、是否和参数有关呢？

**Comment by Facico** [comment]
将min_new_tokens调大一点，beam search生成的时候中间结果比较随机，可能在最后找到一个eos就把后面的断掉了
