### ISSUE TITLE
interaction.py 第158行，返回了两次history

### ISSUE THREAD

**Issue by Rogerspy** [Facico/Chinese-Vicuna#132]
rt

**Comment by Facico** [comment]
感谢关注、这个问题不大的，因为两个history用于更新的东西不同，代码看起来可能不太优雅，可以忽略

**Comment by Rogerspy** [comment]
嗯，我之所以关注到这个问题，是发现clear按钮好像不起作用。我试了几种方式都不行，官方issue也有：https://github.com/gradio-app/gradio/issues/885，下面给出的解决方案我也试了，也不行。你有更好的办法吗？

**Comment by Facico** [comment]
你可以用我们的chat，chat里面实现了比较丰富的按钮

**Comment by Rogerspy** [comment]
> 你可以用我们的chat，chat里面实现了比较丰富的按钮

对于流式生成过程GPU显存不释放你们有什么好的解决办法吗？我看你们代码里（chat.py）只是抛出了这个问题，torch.cuda.empty_cache()好像并没有起作用，显存仍然是满的

**Comment by Facico** [comment]
我们只在OOM的时候用的这个torch.cuda.empty_cache()，你可以在每个回答后面都加一次。类似的问题可以看#66
