### ISSUE TITLE
README.md  mis-inforamtion:  `LLAMA13B is numerically superior to 175B GPT3）` -> 17.5B 

### ISSUE THREAD

**Issue by huide9** [Facico/Chinese-Vicuna#134]
README.md

```
What we need? -> 

Large Language Model：

LLAMA 7B（Of course, if you have a larger machine(such as 3090Ti) can be replaced with a 13B, LLAMA13B is numerically superior to **175B** GPT3）   

```
it supose to be 17.5B  based on below [wiki](https://en.wikipedia.org/wiki/GPT-3#:~:text=The%20architecture%20is%20a%20decoder,parameters%2C%20requiring%20800GB%20to%20store.)   info.

https://en.wikipedia.org/wiki/GPT-3#:~:text=The%20architecture%20is%20a%20decoder,parameters%2C%20requiring%20800GB%20to%20store.

**Comment by Facico** [comment]
The wiki you provided says it's not also 175B ('175 billion parameters')？

**Comment by huide9** [comment]
shoot! I must read screen to much time!
