### ISSUE TITLE
提示 ：ERROR: Could not find a version that satisfies the requirement triton==2.0.0 (from versions: none) 是什么情况？

### ISSUE THREAD

**Issue by davedat** [Facico/Chinese-Vicuna#135]
ERROR: Could not find a version that satisfies the requirement triton==2.0.0 (from versions: none)
ERROR: No matching distribution found for triton==2.0.0

**Comment by fansir** [comment]
一样遇到了这个问题

**Comment by meZhheng** [comment]
windows系统没有triton这个依赖，可以先从下面的链接下载编译过的Windows下二进制，然后安装
https://huggingface.co/r4ziel/xformers_pre_built/blob/main/triton-2.0.0-cp310-cp310-win_amd64.whl
