### ISSUE TITLE
我用这个模型发现已经支持中文，请问是他自己实现的还是组合了本模型

### ISSUE THREAD

**Issue by mushuanli** [Facico/Chinese-Vicuna#142]
我发现这个模型已经支持中文，https://huggingface.co/eachadea/ggml-vicuna-13b-1.1/tree/main
那么是 vicuna本身支持中文，还是因为模型中增加了这个仓库的训练，
或者作者有其他方式训练？

**Comment by LZY-the-boys** [comment]
我们这个仓库建的比standford的vicuna早，两者没有必然的关系。standford的vicuna是见过中文的，但是中文能力不算很强。我们自己训练的相比会对中文更友好一点。
