### ISSUE TITLE
使用您提供的simple_test.py脚本测试，发现token第一个起始字符id是0，识别也是乱码

### ISSUE THREAD

**Issue by leizhu1989** [Facico/Chinese-Vicuna#143]
你好我的环境：
系统：ubuntu 18.04
显卡：V100 *8
transformers版本：4.28.1
tokenizers  ：             0.13.2
sentencepiece   ：       0.1.97

你好，我在使用如下脚本测试：
import sys
import torch
from peft import PeftModel
import transformers
from transformers import LlamaTokenizer, LlamaForCausalLM

#tokenizer = LlamaTokenizer.from_pretrained("/media/sdc/vicuna_model/llama-7b-hf")
tokenizer = LlamaTokenizer.from_pretrained("/media/sdc/vicuna_model/llama-7b-hf", add_eos_token=False, add_bos_token=True)

print(tokenizer.eos_token_id)
print(tokenizer.bos_token_id)
print(tokenizer._convert_token_to_id(tokenizer.bos_token))
print(tokenizer._convert_token_to_id('<s>'))
print(tokenizer._convert_token_to_id('</s>'))

BASE_MODEL = "/media/sdc/vicuna_model/llama-7b-hf"

model = LlamaForCausalLM.from_pretrained(
    BASE_MODEL,
    load_in_8bit=True,
    torch_dtype=torch.float16,
    device_map="auto", #"auto"  
)
model.eval()
inputs = "Hello, Where is the capital of the United States?" #"你好,美国的首都在哪里？"
input_ids = tokenizer(inputs, return_tensors="pt")['input_ids']
print(input_ids)
generation_output = model.generate(
            input_ids=input_ids,
            max_new_tokens=15,
        )
print(generation_output)
print(tokenizer.decode(generation_output[0]))

model = PeftModel.from_pretrained(
        model,
        "/home/ctgcdt/zhulei/NLP/Chinese-Vicuna/lora-Vicuna/checkpoint-final",
        torch_dtype=torch.float16,
        device_map={'': 0} #"": "cpu"  '': 0
    )

inputs = "你好,中国的首都在哪里？" #"你好,美国的首都在哪里？"
input_ids = tokenizer(inputs, return_tensors="pt")['input_ids']
print(input_ids)
#input_ids = input_ids.to(0)
generation_output = model.generate(
            input_ids=input_ids,
            max_new_tokens=15,
        )
print(generation_output)
print(tokenizer.decode(generation_output[0]))

结果是这样：
CUDA SETUP: Loading binary /home/ctgcdt/anaconda3/envs/Chinese_vicuna/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117_nocublaslt.so...
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'. 
The class this function is called from is 'LlamaTokenizer'.
0
0
0
1
2
.........
.........
tensor([[    0, 15043, 29892,  6804,   338,   278,  7483,   310,   278,  3303,
          3900, 29973]])
/home/ctgcdt/anaconda3/envs/Chinese_vicuna/lib/python3.8/site-packages/transformers/generation/utils.py:1219: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
/home/ctgcdt/anaconda3/envs/Chinese_vicuna/lib/python3.8/site-packages/transformers/generation/utils.py:1405: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(
tensor([[    0, 15043, 29892,  6804,   338,   278,  7483,   310,   278,  3303,
          3900, 29973,  7660, 29892,   360, 29889, 29907, 29889,  7660, 29892,
           360, 29889, 29907, 29889,  7660, 29892,   360]])
 ⁇  Hello, Where is the capital of the United States? Washington, D.C. Washington, D.C. Washington, D
tensor([[    0, 29871, 30919, 31076, 29892, 30275, 30356, 30210, 31688, 30769,
         30505,   232,   150,   173, 30755, 30882]])
tensor([[    0, 29871, 30919, 31076, 29892, 30275, 30356, 30210, 31688, 30769,
         30505,   232,   150,   173, 30755, 30882, 29871, 29871, 29871, 29871,
         29871, 29871, 29871, 29871, 29871, 29871, 29871, 29871, 29871, 29871,
         29871]])
 ⁇  你好,中国的首都在哪里？

请问这个是什么原因呢，token解析都不对啊，我下载的7b模型连接：  https://huggingface.co/decapoda-research/llama-7b-hf/tree/main

**Comment by leizhu1989** [comment]
可以了，要重装transformers

**Comment by leizhu1989** [comment]
觉得还是有点不对劲：同上的验证方式，使用您的checkpoint-final模型，我换着问就觉得回答得很离谱，这是正常的吗：
tensor([[    1, 29871, 31201,   236,   138,   141, 30557, 30533, 31539, 30573,
           231,   190,   131, 31882, 30392,   234,   142,   175, 30287, 31352,
         30685, 30210, 30882]])
/home/ctgcdt/anaconda3/envs/Chinese_vicuna/lib/python3.8/site-packages/transformers/generation/utils.py:1211: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
/home/ctgcdt/anaconda3/envs/Chinese_vicuna/lib/python3.8/site-packages/transformers/generation/utils.py:1384: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(
tensor([[    1, 29871, 31201,   236,   138,   141, 30557, 30533, 31539, 30573,
           231,   190,   131, 31882, 30392,   234,   142,   175, 30287, 31352,
         30685, 30210, 30882,    13, 30533, 31539, 30392,   234,   142,   175,
         30287, 31352, 30685, 30210, 30214, 31570, 30573,   232]])
 解释下地球为什么是独一无二的？
地球是独一无二的，因为�
tensor([[    1, 29871, 30287,   232,   146,   168, 31852, 31201,   236,   138,
           141, 30573,   231,   190,   131, 31882, 30533, 31539, 30392,   234,
           142,   175, 30287, 31352, 30685, 30210, 30882]])
tensor([[    1, 29871, 30287,   232,   146,   168, 31852, 31201,   236,   138,
           141, 30573,   231,   190,   131, 31882, 30533, 31539, 30392,   234,
           142,   175, 30287, 31352, 30685, 30210, 30882,    13, 30533, 31539,
         30392,   234,   142,   175, 30287, 31352, 30685, 30210, 30214, 31570,
         30573,   232,   177,   134, 30392, 30287, 30502,   232,   151,   178,
         30287, 30210, 30448, 30900, 30214,   232,   177,   134, 30210,   234,
           190,   152,   234,   160,   131,   232,   177,   134, 30210,   233,
           163,   187,   235,   193,   180,   235,   142,   169, 30214,   232,
           177,   134, 30210,   234,   190,   152,   234,   160,   131,   232,
           177,   134, 30210,   233,   179,   151,   232,   148,   182, 30214,
           232,   177,   134, 30210,   234,   190,   152,   234,   160,   131,
           232,   177,   134, 30210, 30716, 30214,   232,   177,   134, 30210,
           234,   190,   152,   234,   160,   131,   232,   177,   134, 30210,
           233,   187,   157,   233,   179, 30267,    13, 30003, 29871,   232,
           179,   191,   232,   179,    13, 30533, 31539, 30392,   234,   142,
           175, 30287, 31352, 30685, 30210]])
 一句话解释为什么地球是独一无二的？
地球是独一无二的，因为它是一个唯一的行星，它的绕着它的核辱苦，它的绕着它的气味，它的绕着它的水，它的绕着它的渚��。
— 尼��
地球是独一无二的

用您提供的问句回答的还行(设置了最大长度128)，是因为模型还不够强吗：
tensor([[    1, 15043, 29892,  6804,   338,   278,  7483,   310,   278,  3303,
          3900, 29973]])
/home/ctgcdt/anaconda3/envs/Chinese_vicuna/lib/python3.8/site-packages/transformers/generation/utils.py:1211: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
/home/ctgcdt/anaconda3/envs/Chinese_vicuna/lib/python3.8/site-packages/transformers/generation/utils.py:1384: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cpu, whereas the model is on cuda. You may experience unexpected behaviors or slower generation. Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cuda') before running `.generate()`.
  warnings.warn(
tensor([[    1, 15043, 29892,  6804,   338,   278,  7483,   310,   278,  3303,
          3900, 29973,    13,  1576,  7483,   310,   278,  3303,  3900,   338,
          7660, 29892,   360, 29889, 29907, 29889,    13]])
 Hello, Where is the capital of the United States?
The capital of the United States is Washington, D.C.

tensor([[    1, 29871, 30919, 31076, 29892, 30275, 30356, 30210, 31688, 30769,
         30505,   232,   150,   173, 30755, 30882]])
tensor([[    1, 29871, 30919, 31076, 29892, 30275, 30356, 30210, 31688, 30769,
         30505,   232,   150,   173, 30755, 30882,    13, 30275, 30356, 30210,
         31688, 30769, 30392, 30662, 30675, 30267,    13, 30662, 30675, 30392,
         30275, 30356, 30210, 31688, 30769, 30214, 30953, 30392, 30793, 30967,
         30429, 30878, 30257, 30210, 30626, 30461, 30577, 30287, 30267,    13,
         30662, 30675, 30392, 30287, 30502,   233,   142,   168, 30417,   231,
           187,   179, 31730,   232,   145,   137, 30911, 30503, 30333, 30705,
           236,   132,   154,   231,   189,   164, 30210, 30626, 30461, 30214,
         30953, 30392, 30275, 30356, 30210, 31014, 31032, 30330, 31412,   233,
           184,   145, 30330, 30333, 30705, 30330, 31030, 31615, 30330, 31023,
         31635, 30330,   232,   171,   180, 31616, 31184, 30908, 30698, 30626,
         30461, 30267,    13, 30662, 30675,   233,   142,   168, 30417,   235,
           177,   187, 30923,   235,   148,   154, 30548, 30210, 31495, 30940,
         30214, 30847, 31969,   232,   177,   174, 30330, 30408,   232,   160,
           158, 30330, 31143, 30626]])
 你好,中国的首都在哪里？
中国的首都是北京。
北京是中国的首都，也是世界上最大的城市之一。
北京是一个拥有丰富历史和文化遗亡的城市，也是中国的政治、经济、文化、科技、教育、娱乐等重要城市。
北京拥有许多著名的景点，如故宫、天坛、长城


我自己取merge.json中前面2万条语料跑了一下，发现问的这几个问题都回答的不行，但是训练loss在0.87左右，8张V100用的7b模型，.half()训练的方式

**Comment by Facico** [comment]
你可以使用我们的推理脚本试试，需要把beam_num设置成>1

**Comment by leizhu1989** [comment]
感谢大佬及时回复，我的服务器没外网啊，您说的是generate.py这个脚本吗，这个需要在网页查看输入吧，服务器也是远程访问，没界面也没外网

**Comment by Facico** [comment]
如果你服务器可以用vscode打开的话，vscode是可以帮你端口转发的。
还有一种方式是你可以参照我们[generate里面的打法](https://github.com/Facico/Chinese-Vicuna/blob/master/generate.py#L160)把相关的参数加上去

**Comment by Facico** [comment]
和我上面给你的代码一样的，我直接帮你摘出来了。。。
```
from transformers import GenerationConfig
generation_config = GenerationConfig(
        temperature=temperature,
        top_p=top_p,
        top_k=top_k,
        num_beams=num_beams,
        bos_token_id=1,
        eos_token_id=2,
        pad_token_id=0,
        max_new_tokens=max_new_tokens, # max_length=max_new_tokens+input_sequence
        min_new_tokens=min_new_tokens, # min_length=min_new_tokens+input_sequence
        **kwargs,
    )

generation_output = model.generate(
                input_ids=input_ids,
                generation_config=generation_config,
                return_dict_in_generate=True,
                output_scores=False,
                repetition_penalty=1.3,
            )
output = generation_output.sequences[0]
```

**Comment by leizhu1989** [comment]
明白了，谢谢大佬指点

**Comment by leizhu1989** [comment]
大佬，修改的代码和测试如下：
import sys
import torch
from peft import PeftModel
import transformers
from transformers import LlamaTokenizer, LlamaForCausalLM, GenerationConfig

#tokenizer = LlamaTokenizer.from_pretrained("/media/sdc/vicuna_model/llama-7b-hf")
tokenizer = LlamaTokenizer.from_pretrained("/media/sdc/vicuna_model/llama-7b-hf", add_eos_token=False, add_bos_token=True)
#tokenizer = LlamaTokenizer.from_pretrained("/home/ctgcdt/zhulei/NLP/Chinese-Vicuna/lora-Vicuna-7B", add_eos_token=False, add_bos_token=True)

print(tokenizer.eos_token_id)
print(tokenizer.bos_token_id)
print(tokenizer._convert_token_to_id(tokenizer.bos_token))
print(tokenizer._convert_token_to_id('<s>'))
print(tokenizer._convert_token_to_id('</s>'))

generation_config = GenerationConfig(
    temperature=0.1,
    top_p=0.75,
    top_k=40,
    num_beams=4,
    bos_token_id=1,
    eos_token_id=2,
    pad_token_id=0,
    max_new_tokens=128, # max_length=max_new_tokens+input_sequence
    min_new_tokens=1, # min_length=min_new_tokens+input_sequence
)

BASE_MODEL = "/media/sdc/vicuna_model/llama-7b-hf"

model = LlamaForCausalLM.from_pretrained(
    BASE_MODEL,
    load_in_8bit=False,
    torch_dtype=torch.float16,
    device_map="auto", #"auto"  
)
model = PeftModel.from_pretrained(
        model,
        "/home/ctgcdt/zhulei/NLP/Chinese-Vicuna/lora-Vicuna/checkpoint-final", #/home/ctgcdt/zhulei/NLP/Chinese-Vicuna/lora-Vicuna-7B   /home/ctgcdt/zhulei/NLP/Chinese-Vicuna/lora-Vicuna/checkpoint-final
        torch_dtype=torch.float16,
        device_map={'': 0} #"": "cpu"  '': 0
    )

model.half()
model.eval
inputs = "你好,中国的首都在哪里？" #"你好,美国的首都在哪里？"
input_ids = tokenizer(inputs, return_tensors="pt")['input_ids'].to("cuda")
generation_output = model.generate(
    input_ids=input_ids,
    generation_config=generation_config,
    return_dict_in_generate=True,
    output_scores=False,
    repetition_penalty=1.3,
)
output = generation_output.sequences[0]
output = tokenizer.decode(output)
print(output)

输出结果：
你好,中国的首都在哪里？中国的首都是哪里？中国的首都是哪里？中国的首都是哪里？中国的首都是哪里？中国的首都是哪里？中国的首都是哪里？中国的首都是哪里？中国的首都是哪里？中国的首都是哪里？中国的首都是哪里？中国的首都是哪里？中国的首都是

是不是哪里搞错了呢

**Comment by leizhu1989** [comment]
@Facico 调到了2.0，感觉还是有点离谱啊

 一句话解释为什么地球是独一无二的？
地球是独一无二的，因为它是我们所在的星球，也是我们生命中最重要的家园。
地球是独一无二的，因为它是我们所在的星球，也是我们生命中最重要的家园。
地球是独一无二的，因为它是我们所在的星球，也是我们生命中最重要的家园。
地

 一句话解释为什么地球是独一无二的？
地球是独一无二的，因为它是我们所在的家园，我们必须保护它。
地球是独一无二的，因为它是我们所在的家园，我们必须保护它。
地球是独一无二的，因为它是我们所在的家园，我们必须保护它。
地

大佬，请问代码有明显的问题吗

**Comment by Facico** [comment]
话说你代码里有加instruction吗，比如我们在generate里面的
```
if input:
        return f"""Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{instruction}

### Input:
{input}

### Response:"""
    else:
        return f"""Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
{instruction}

### Response:"""
```

**Comment by leizhu1989** [comment]
这个确实没加，加上了感觉稍微好点，直接把大佬说的代码加进去了，这样就对的吧
 Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
你好,中国的首都在哪里？

### Response:
中国的首都是北京。

**Comment by Facico** [comment]
其实还有### Instruction:和### Response:这种格式

**Comment by leizhu1989** [comment]
嗯嗯，重新测了，有这样的格式，谢谢大佬指点
