### ISSUE TITLE
finetune_others_continue.sh 报AttributeError: 'NoneType' object has no attribute 'print_trainable_parameters'

### ISSUE THREAD

**Issue by qqshuqain** [Facico/Chinese-Vicuna#144]
TOT_CUDA="0"
CUDA_NUM=1
PORT="12345"

DATA_PATH="./sample/merge_sample.json" 
OUTPUT_PATH="lora-Vicuna"
MODEL_PATH="/data/run01/scz0csk/data/decapoda-research/llama-7b-hf"
lora_checkpoint="./lora-Vicuna/checkpoint-11600"
from_data_beginning=True # False
TEST_SIZE=1

CUDA_VISIBLE_DEVICES=${TOT_CUDA} torchrun --nproc_per_node=$CUDA_NUM --master_port=$PORT finetune.py \
--data_path $DATA_PATH \
--output_path $OUTPUT_PATH \
--model_path $MODEL_PATH \
--eval_steps 200 \
--save_steps 200 \
--test_size $TEST_SIZE \
--resume_from_checkpoint $lora_checkpoint \
--ignore_data_skip $from_data_beginning

执行这个命令是报下面错误，

0%|          | 0/1 [00:00<?, ?it/s]
100%|██████████| 1/1 [00:00<00:00,  1.44it/s]
100%|██████████| 1/1 [00:00<00:00,  1.44it/s]
Restarting from ./lora-Vicuna/checkpoint-11600/pytorch_model.bin
/data/run01/scz0csk/llama/chinesevicuna/finetune.py:124: UserWarning: epoch 3 replace to the base_max_steps 17298
  warnings.warn("epoch {} replace to the base_max_steps {}".format(EPOCHS, base_max_steps))
Traceback (most recent call last):
  File "/data/run01/scz0csk/llama/chinesevicuna/finetune.py", line 133, in <module>
    model.print_trainable_parameters()
AttributeError: 'NoneType' object has no attribute 'print_trainable_parameters'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2613) of binary: /HOME/scz0csk/.conda/envs/py39/bin/python
Traceback (most recent call last):
  File "/HOME/scz0csk/.conda/envs/py39/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/HOME/scz0csk/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/HOME/scz0csk/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/HOME/scz0csk/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/HOME/scz0csk/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/HOME/scz0csk/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-09_22:36:38
  host      : g0155.para.ai
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2613)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by Facico** [comment]
可以去看一下我们的[note](https://github.com/Facico/Chinese-Vicuna/blob/master/docs/notes.md)，类似的问题很多

**Comment by Apple-zly** [comment]
你好，我finetune_others_continue.sh 微调 finetune_4bit.py 报同样的错误，安装作者说的修改了peft和transformer的版本，还是报同样的错误，请问您解决这个问题了吗？盼回复！谢谢！

**Comment by summer-silence** [comment]
@Apple-zly 请问后来是如何解决的呢

**Comment by 96005900** [comment]
请问你是如何解决的，我也遇到了同样的问题
