### ISSUE TITLE
请问用4090单卡是否可以lora微调13b模型？

### ISSUE THREAD

**Issue by Kkkkkiradd** [Facico/Chinese-Vicuna#146]
请问用4090单卡是否可以微调13b模型？不行的话两张4090能否完成微调？求大佬解答

**Comment by LZY-the-boys** [comment]
可以，长度2048也可以支持

**Comment by Kkkkkiradd** [comment]
> 可以，长度2048也可以支持

感谢大佬回答！

**Comment by xianghui123** [comment]
卧槽，怎么做到搞2048啊？ 我用的7B, 调到512都内存超了，大佬教教我

**Comment by Facico** [comment]
@xianghui123 你可以试着把mirco batch size开小一点

**Comment by xianghui123** [comment]
@Facico 感谢解答，跑起来了，我去学习下这些参数的含义

**Comment by Combustible-material** [comment]
我3060-12G能跑Llama-13B吗？必须24G吗？

**Comment by Facico** [comment]
@Combustible-material 3060不行，7B的应该可以
