### ISSUE TITLE
cuda out of memory in saving steps. 

### ISSUE THREAD

**Issue by jzsbioinfo** [Facico/Chinese-Vicuna#147]
同样的环境，之前用finetune.py lora训练llama 13b没有问题，现在用A100训练llama 30b，出现问题。
transformers.Trainer，每次到save_step要保存模型的时候，没保存完直接cuda out of memory，google半天没找到解决方法，想在这里讨论下。

具体报错如下，可以看到在eval之后，要保存模型（checkpoint）的时候报错。

{'loss': 1.7642, 'learning_rate': 5.9999999999999995e-05, 'epoch': 0.03}                                                                                           
{'loss': 1.3664, 'learning_rate': 0.00011999999999999999, 'epoch': 0.06}                                                                                           
{'eval_loss': 1.1047903299331665, 'eval_runtime': 27.1525, 'eval_samples_per_second': 36.829, 'eval_steps_per_second': 1.179, 'epoch': 0.07}                       
  2%|██▉                                                                                                                      | 50/2019 [24:43<15:52:05, 29.01s/it╭
─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮                                                                
│ /data/jiangzhisheng/work/chinese_vicuna/Chinese-Vicuna/finetune_8bit_33B.py:261 in <module>      │
│                                                                                                  │
│   258                                                                                            │
│   259 print("\n If there's a warning about missing keys above, please disregard :)")             │
│   260                                                                                            │
│ ❱ 261 trainer.train(resume_from_checkpoint=args.resume_from_checkpoint)                          │
│   262                                                                                            │
│   263 model.save_pretrained(OUTPUT_DIR)                                                          │
│   264                                                                                            │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/transformers/trainer.py:166 │
│ 2 in train                                                                                       │
│                                                                                                  │
│   1659 │   │   inner_training_loop = find_executable_batch_size(                                 │
│   1660 │   │   │   self._inner_training_loop, self._train_batch_size, args.auto_find_batch_size  │
│   1661 │   │   )                                                                                 │
│ ❱ 1662 │   │   return inner_training_loop(                                                       │
│   1663 │   │   │   args=args,                                                                    │
│   1664 │   │   │   resume_from_checkpoint=resume_from_checkpoint,                                │
│   1665 │   │   │   trial=trial,                                                                  │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/transformers/trainer.py:200 │
│ 6 in _inner_training_loop                                                                        │
│                                                                                                  │
│   2003 │   │   │   │   │   self.state.epoch = epoch + (step + 1 + steps_skipped) / steps_in_epo  │
│   2004 │   │   │   │   │   self.control = self.callback_handler.on_step_end(args, self.state, s  │
│   2005 │   │   │   │   │                                                                         │
│ ❱ 2006 │   │   │   │   │   self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_k  │
│   2007 │   │   │   │   else:                                                                     │
│   2008 │   │   │   │   │   self.control = self.callback_handler.on_substep_end(args, self.state  │
│   2009                                                                                           │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/transformers/trainer.py:229 │
│ 1 in _maybe_log_save_evaluate                                                                    │
│                                                                                                  │
│   2288 │   │   │   self._report_to_hp_search(trial, self.state.global_step, metrics)             │
│   2289 │   │                                                                                     │
│   2290 │   │   if self.control.should_save:                                                      │
│ ❱ 2291 │   │   │   self._save_checkpoint(model, trial, metrics=metrics)                          │
│   2292 │   │   │   self.control = self.callback_handler.on_save(self.args, self.state, self.con  │
│   2293 │                                                                                         │
│   2294 │   def _load_rng_state(self, checkpoint):                                                │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/transformers/trainer.py:234 │
│ 8 in _save_checkpoint                                                                            │
│                                                                                                  │
│   2345 │   │                                                                                     │
│   2346 │   │   run_dir = self._get_output_dir(trial=trial)                                       │
│   2347 │   │   output_dir = os.path.join(run_dir, checkpoint_folder)                             │
│ ❱ 2348 │   │   self.save_model(output_dir, _internal_call=True)                                  │
│   2349 │   │   if self.deepspeed:                                                                │
│   2350 │   │   │   # under zero3 model file itself doesn't get saved since it's bogus! Unless d  │
│   2351 │   │   │   # config `stage3_gather_16bit_weights_on_model_save` is True                  │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/transformers/trainer.py:283 │
│ 0 in save_model                                                                                  │
│                                                                                                  │
│   2827 │   │   │   │   │   self.deepspeed.save_checkpoint(output_dir)                            │
│   2828 │   │                                                                                     │
│   2829 │   │   elif self.args.should_save:                                                       │
│ ❱ 2830 │   │   │   self._save(output_dir)                                                        │
│   2831 │   │                                                                                     │
│   2832 │   │   # Push to the Hub when `save_model` is called by the user.                        │
│   2833 │   │   if self.args.push_to_hub and not _internal_call:                                  │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/transformers/trainer.py:287 │
│ 3 in _save                                                                                       │
│                                                                                                  │
│   2870 │   │   # They can then be reloaded using `from_pretrained()`                             │
│   2871 │   │   if not isinstance(self.model, PreTrainedModel):                                   │
│   2872 │   │   │   if state_dict is None:                                                        │
│ ❱ 2873 │   │   │   │   state_dict = self.model.state_dict()                                      │
│   2874 │   │   │                                                                                 │
│   2875 │   │   │   if isinstance(unwrap_model(self.model), PreTrainedModel):                     │
│   2876 │   │   │   │   unwrap_model(self.model).save_pretrained(                                 │
│                                                                                                  │
│ /data/jiangzhisheng/work/chinese_vicuna/Chinese-Vicuna/finetune_8bit_33B.py:253 in <lambda>      │
│                                                                                                  │
│   250                                                                                            │
│   251 old_state_dict = model.state_dict                                                          │
│   252 model.state_dict = (                                                                       │
│ ❱ 253 │   lambda self, *_, **__: get_peft_model_state_dict(self, old_state_dict())               │
│   254 ).__get__(model, type(model))                                                              │
│   255                                                                                            │
│   256 if torch.__version__ >= "2" and sys.platform != "win32":                                   │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/torch/nn/modules/module.py: │
│ 1448 in state_dict                                                                               │
│                                                                                                  │
│   1445 │   │   self._save_to_state_dict(destination, prefix, keep_vars)                          │
│   1446 │   │   for name, module in self._modules.items():                                        │
│   1447 │   │   │   if module is not None:                                                        │
│ ❱ 1448 │   │   │   │   module.state_dict(destination=destination, prefix=prefix + name + '.', k  │
│   1449 │   │   for hook in self._state_dict_hooks.values():                                      │
│   1450 │   │   │   hook_result = hook(self, destination, prefix, local_metadata)                 │
│   1451 │   │   │   if hook_result is not None:                                                   │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/torch/nn/modules/module.py: │
│ 1448 in state_dict                                                                               │
│                                                                                                  │
│   1445 │   │   self._save_to_state_dict(destination, prefix, keep_vars)                          │
│   1446 │   │   for name, module in self._modules.items():                                        │
│   1447 │   │   │   if module is not None:                                                        │
│ ❱ 1448 │   │   │   │   module.state_dict(destination=destination, prefix=prefix + name + '.', k  │
│   1449 │   │   for hook in self._state_dict_hooks.values():                                      │
│   1450 │   │   │   hook_result = hook(self, destination, prefix, local_metadata)                 │
│   1451 │   │   │   if hook_result is not None:                                                   │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/torch/nn/modules/module.py: │
│ 1448 in state_dict                                                                               │
│                                                                                                  │
│   1445 │   │   self._save_to_state_dict(destination, prefix, keep_vars)                          │
│   1446 │   │   for name, module in self._modules.items():                                        │
│   1447 │   │   │   if module is not None:                                                        │
│ ❱ 1448 │   │   │   │   module.state_dict(destination=destination, prefix=prefix + name + '.', k  │
│   1449 │   │   for hook in self._state_dict_hooks.values():                                      │
│   1450 │   │   │   hook_result = hook(self, destination, prefix, local_metadata)                 │
│   1451 │   │   │   if hook_result is not None:                                                   │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/torch/nn/modules/module.py: │
│ 1448 in state_dict                                                                               │
│                                                                                                  │
│   1445 │   │   self._save_to_state_dict(destination, prefix, keep_vars)                          │
│   1446 │   │   for name, module in self._modules.items():                                        │
│   1447 │   │   │   if module is not None:                                                        │
│ ❱ 1448 │   │   │   │   module.state_dict(destination=destination, prefix=prefix + name + '.', k  │
│   1449 │   │   for hook in self._state_dict_hooks.values():                                      │
│   1450 │   │   │   hook_result = hook(self, destination, prefix, local_metadata)                 │
│   1451 │   │   │   if hook_result is not None:                                                   │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/torch/nn/modules/module.py: │
│ 1448 in state_dict                                                                               │
│                                                                                                  │
│   1445 │   │   self._save_to_state_dict(destination, prefix, keep_vars)                          │
│   1446 │   │   for name, module in self._modules.items():                                        │
│   1447 │   │   │   if module is not None:                                                        │
│ ❱ 1448 │   │   │   │   module.state_dict(destination=destination, prefix=prefix + name + '.', k  │
│   1449 │   │   for hook in self._state_dict_hooks.values():                                      │
│   1450 │   │   │   hook_result = hook(self, destination, prefix, local_metadata)                 │
│   1451 │   │   │   if hook_result is not None:                                                   │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/torch/nn/modules/module.py: │
│ 1448 in state_dict                                                                               │
│                                                                                                  │
│   1445 │   │   self._save_to_state_dict(destination, prefix, keep_vars)                          │
│   1446 │   │   for name, module in self._modules.items():                                        │
│   1447 │   │   │   if module is not None:                                                        │
│ ❱ 1448 │   │   │   │   module.state_dict(destination=destination, prefix=prefix + name + '.', k  │
│   1449 │   │   for hook in self._state_dict_hooks.values():                                      │
│   1450 │   │   │   hook_result = hook(self, destination, prefix, local_metadata)                 │
│   1451 │   │   │   if hook_result is not None:                                                   │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/torch/nn/modules/module.py: │
│ 1448 in state_dict                                                                               │
│                                                                                                  │
│   1445 │   │   self._save_to_state_dict(destination, prefix, keep_vars)                          │
│   1446 │   │   for name, module in self._modules.items():                                        │
│   1447 │   │   │   if module is not None:                                                        │
│ ❱ 1448 │   │   │   │   module.state_dict(destination=destination, prefix=prefix + name + '.', k  │
│   1449 │   │   for hook in self._state_dict_hooks.values():                                      │
│   1450 │   │   │   hook_result = hook(self, destination, prefix, local_metadata)                 │
│   1451 │   │   │   if hook_result is not None:                                                   │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/torch/nn/modules/module.py: │
│ 1445 in state_dict                                                                               │
│                                                                                                  │
│   1442 │   │   if hasattr(destination, "_metadata"):                                             │
│   1443 │   │   │   destination._metadata[prefix[:-1]] = local_metadata                           │
│   1444 │   │                                                                                     │
│ ❱ 1445 │   │   self._save_to_state_dict(destination, prefix, keep_vars)                          │
│   1446 │   │   for name, module in self._modules.items():                                        │
│   1447 │   │   │   if module is not None:                                                        │
│   1448 │   │   │   │   module.state_dict(destination=destination, prefix=prefix + name + '.', k  │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/bitsandbytes/nn/modules.py: │
│ 268 in _save_to_state_dict                                                                       │
│                                                                                                  │
│   265 │   │                                                                                      │
│   266 │   │   try:                                                                               │
│   267 │   │   │   if reorder_layout:                                                             │
│ ❱ 268 │   │   │   │   self.weight.data = undo_layout(self.state.CxB, self.state.tile_indices)    │
│   269 │   │   │                                                                                  │
│   270 │   │   │   super()._save_to_state_dict(destination, prefix, keep_vars)                    │
│   271                                                                                            │
│                                                                                                  │
│ /data/jiangzhisheng/anaconda3/envs/llama/lib/python3.9/site-packages/bitsandbytes/autograd/_func │
│ tions.py:100 in undo_layout                                                                      │
│                                                                                                  │
│    97 │   outputs[tile_indices.flatten()] = tensor                                               │
│    98 │   outputs = outputs.reshape(tile_rows, tile_cols, cols // tile_cols, rows // tile_rows   │
│    99 │   outputs = outputs.permute(3, 0, 2, 1)  # (rows // tile_rows, tile_rows), (cols // ti   │
│ ❱ 100 │   return outputs.reshape(rows, cols).contiguous()                                        │
│   101                                                                                            │
│   102                                                                                            │
│   103 class MatMul8bit(torch.autograd.Function):                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 44.00 MiB (GPU 0; 79.21 GiB total capacity; 74.28 GiB already allocated; 43.56 MiB free; 77.45 GiB reserved
in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and 
PYTORCH_CUDA_ALLOC_CONF

**Comment by Facico** [comment]
这个问题在我们的[NOTE](https://github.com/Facico/Chinese-Vicuna/blob/master/docs/notes.md)里面有，可以看一下
