### ISSUE TITLE
使用定时器方式监测断点执行finetune

### ISSUE THREAD

**Issue by grantchenhuarong** [Facico/Chinese-Vicuna#150]
因为在finetune的过程当中，会因为各种情况（数据质量影响，程序代码健壮性不足，系统环境受干扰等），训练过程异常退出，且原因也难明。所以需要能够自动进行断点重新启动训练的执行，才不会浪费漫漫长夜的美好时光，争分夺秒的利用资源进行训练。

基本思路是，使用定时器每N分钟监测一下，利用ps监测finetune进程。如果其不存在了，就去选择一个最近保留的Lora checkpoint权重文件，重新启动起来就好。

需要确保在N分钟内，训练进程能够完全启动哈。

昨天晚上就是22点多停了，睡醒才发现完全没跑下去，就写了这么个脚本，扔到cron里边监控了。

##                */15 * * * * bash /home/ai/src/Chinese-Vicuna/finetune_others_continue_cron.sh >>/home/ai/src/Chinese-Vicuna/shici9.log 2>&1

#!/bin/bash

#设置执行参数
. /etc/profile
source ~/anaconda3/etc/profile.d/conda.sh
BASE_PATH="/home/ai/src/Chinese-Vicuna/"
LOG=$BASE_PATH"finetune_others.log"
TRAIN_LOG=$BASE_PATH"shici9.log"

TOT_CUDA="0"
CUDAs=(${TOT_CUDA//,/ })
CUDA_NUM=${#CUDAs[@]}
PORT="12345"

MODEL_PATH="/data/ftp/models/llama/7b-hf/"
DATA_PATH=$BASE_PATH"data/instructions1.json"
LORA_CHECKPOINT=$BASE_PATH"lora-Vicuna/checkpoint-11600"
OUTPUT_PATH=$BASE_PATH"lora-Vicuna/shici9/"
from_data_beginning=True # False
TEST_SIZE=3

echo $DATA_PATH>>$LOG
echo $LORA_CHECKPOINT>>$LOG
echo $OUTPUT_PATH>>$LOG

#判断进程是否已经挂掉
if [ $(ps -ef|grep 'finetune.py'|grep -v grep |wc -l) -le 0 ]; then
  #记录重新启动日志
  echo "$(date +%c) 重新启动finetune程序">>$LOG

  #判断是否已经有新的checkpoint权重生成，如有则变更LORA_CHECKPOINT后断点启动
  checkpoint=`ls -t ${OUTPUT_PATH}|head -n1|awk '{print $0}'`
  RET=$?
  if [ $RET -ne 0 ] || [ -z $checkpoint ]; then
    echo "$(date +%c) 未生成有效的checkpoint权重文件: 默认checkpoint-11600启动">>$LOG
  else
    #设置最新的断点续传启动脚本
    echo "$(date +%c) 重新启动checkpoint权重文件1: ${checkpoint}">>$LOG
    LORA_CHECKPOINT="${OUTPUT_PATH}${checkpoint}"
    echo "$(date +%c) 重新启动checkpoint权重文件2: ${LORA_CHECKPOINT}">>$LOG
  fi

  #激活环境
  conda activate chinesevicuna

  #启动程序
  #CUDA_VISIBLE_DEVICES=${TOT_CUDA} torchrun --nproc_per_node=$CUDA_NUM --master_port=$PORT finetune.py \
  #--data_path $DATA_PATH \
  #--output_path $OUTPUT_PATH \
  #--model_path $MODEL_PATH \
  #--eval_steps 200 \
  #--save_steps 200 \
  #--test_size $TEST_SIZE \
  #--resume_from_checkpoint $LORA_CHECKPOINT \
  #--ignore_data_skip $from_data_beginning

  cd $BASE_PATH
  python finetune.py \
  --data_path $DATA_PATH \
  --output_path $OUTPUT_PATH \
  --model_path $MODEL_PATH \
  --eval_steps 100 \
  --save_steps 100 \
  --test_size $TEST_SIZE \
  --resume_from_checkpoint $LORA_CHECKPOINT \
  --ignore_data_skip $from_data_beginning

  echo "$(date +%c) 重新启动fintune_others_continue成功">>$LOG
fi

**Comment by grantchenhuarong** [comment]
[finetune_others_continue_cron.zip](https://github.com/Facico/Chinese-Vicuna/files/11459322/finetune_others_continue_cron.zip)

**Comment by LZY-the-boys** [comment]
很好的补充，我们刚刚打开了discussion，可以放在[那里](https://github.com/Facico/Chinese-Vicuna/discussions)
