### ISSUE TITLE
使用需要遵循的协议

### ISSUE THREAD

**Issue by yuanjing-jane** [Facico/Chinese-Vicuna#153]
你好，没有在readme中看到模型的权重的使用（包括学术，商业等）则需要遵循协议？请问是否可以补充？

**Comment by Facico** [comment]
因为用到的数据问题我们不同数据训练出的模型协议可能不一样，我们在huggingface的模型有不同的协议，一个是gpl3.0一个是apache-2.0。（设计到guanaco的我们都是gpl3.0，其他的就是apache-2.0）
