### ISSUE TITLE
requeirements中给的https翻墙也会出现404问题

### ISSUE THREAD

**Issue by 153zml** [Facico/Chinese-Vicuna#155]
网址https://github.com/huggingface/peft@e536616888d51b453ed354a6f1e243fecb02ea08无法访问

**Comment by Facico** [comment]
这是git clone用的网址，正常能访问的网址是这样的：https://github.com/huggingface/peft/tree/e536616888d51b453ed354a6f1e243fecb02ea08

**Comment by 153zml** [comment]
- 明白您意思了，可是还是存在一个问题，没有分支e536616888

**Comment by 153zml** [comment]
![7d26628714e165febca86de4c9a9f91](https://github.com/Facico/Chinese-Vicuna/assets/57134637/88c6f60a-25fd-4fc6-87ae-539b5c4bdf35)

**Comment by Facico** [comment]
这不是分支，这是一个commit hash。。。

**Comment by 153zml** [comment]
明白了明白了，谢谢您
