### ISSUE TITLE
用finetune_others_continue.sh自己训练的数据，行4-bit量化后在llama回答不了，其他的问题也比较乱

### ISSUE THREAD

**Issue by qqshuqain** [Facico/Chinese-Vicuna#157]
用finetune_others_continue.sh自己训练的数据，行4-bit量化后在llama回答不了，其他的问题也比较乱。是我使用方法不对么？
1。问的数据就是训练的数据，提问和input 一样

**Comment by qqshuqain** [comment]
一下是我的生成步骤，各位大侠帮忙看看那一步出问题了
1.finetune_others_continue.sh  

配置
DATA_PATH="./sample/alpaca_data_jr_01.json" 
OUTPUT_PATH="lora-Vicuna"
MODEL_PATH="/data/run01/scz0csk/data/decapoda-research/llama-7b-hf"
lora_checkpoint="./lora-Vicuna/checkpoint-11600"

  生成chinesevicuna/lora-jr/checkpoint-17200。。。
2.merge_lora.py
model_path：decapoda-research/llama-7b-hf 和lora_path：chinesevicuna/lora-jr 生成chinesevicuna/lora-jr-with-lora/consolidated.00.pth
3.convert_pth_to_ggml.py
   consolidated.00.pth 生成 ggml-model-f16.bin
4.quantize.exe
 ggml-model-f16.bin 生成ggml-model-q4_0.bin

**Comment by wangrui6** [comment]
@qqshuqain 自己训练数据集的速度如何？ 有发现很慢吗？你说一下你的hardware和数据量以及最后花费了大概多久吗？
