### ISSUE TITLE
finetune_deepspeed.py A100 80G 单卡跑不起来，显存不足

### ISSUE THREAD

**Issue by greatewei** [Facico/Chinese-Vicuna#166]
deepspeed 需要多少机器资源才能运行，并且训练时间能够提升多少

**Comment by Facico** [comment]
你跑的啥模型

**Comment by Facico** [comment]
你是用的全量参数微调吗，或者你把--deepspeed能正常跑吗

**Comment by greatewei** [comment]
> 你是用的全量参数微调吗，或者你把--deepspeed能正常跑吗

也不行，不过不能提升训练速度，我就不进行尝试了😁

**Comment by Facico** [comment]
你用我们的finetune_chat那个代码是比原来的finetune的代码要快一点的

**Comment by reverse-2020** [comment]
我也是，我用的是3090，跑finetune.py可以正常训练，出结果，使用finetune_deepspeed,提示OOM

**Comment by Facico** [comment]
> 我也是，我用的是3090，跑finetune.py可以正常训练，出结果，使用finetune_deepspeed,提示OOM

finetune_deepspeed没开8bit肯定比finetune需要的显存多，因为有些卡用不了8bit才写了那个代码。但相同配置3090/4090是能跑起来的

**Comment by reverse-2020** [comment]
> > 我也是，我用的是3090，跑finetune.py可以正常训练，出结果，使用finetune_deepspeed,提示OOM
> 
> finetune_deepspeed没开8bit肯定比finetune需要的显存多，因为有些卡用不了8bit才写了那个代码。但相同配置3090/4090是能跑起来的

感谢回复，我再试试看
