### ISSUE TITLE
merge.json无法下载

### ISSUE THREAD

**Issue by topshu** [Facico/Chinese-Vicuna#174]
colab上执行：
!gdown "https://drive.google.com/uc?id=1tzXVhS74m-EtoFot7hEc005LDeZGPit_" -O merge.json
提示：
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1tzXVhS74m-EtoFot7hEc005LDeZGPit_ 

从浏览器上也无法下载这个文件

**Comment by Facico** [comment]
感谢，他这个链接可能过期了，我生成了一个新的链接：https://drive.google.com/file/d/1ZQ4xKh1s_UUwbmc9it8EKHFft0M1iFSZ/view?usp=share_link

不过你也可以到huggingface的链接下载
