### ISSUE TITLE
你好，训练是正常的，但是一到模型保存的step就会显存爆炸，很奇怪，保存模型为啥会额外占用显存呢

### ISSUE THREAD

**Issue by wangfudong65** [Facico/Chinese-Vicuna#178]

**Comment by Facico** [comment]
检查一下bitsandbytes版本
你的问题可以参考这里：https://github.com/Facico/Chinese-Vicuna/blob/master/docs/notes.md#oomout-of-memory%E7%88%86%E6%98%BE%E5%AD%98

**Comment by wangfudong65** [comment]
> 检查一下bitsandbytes版本 你的问题可以参考这里：https://github.com/Facico/Chinese-Vicuna/blob/master/docs/notes.md#oomout-of-memory%E7%88%86%E6%98%BE%E5%AD%98

我看看，感谢

**Comment by xuehunmu** [comment]
我保存的时候也是显存爆炸了，重新建了个虚拟环境就正常了
