### ISSUE TITLE
prompt的这些内容是否是多余的，占用了token空间?

### ISSUE THREAD

**Issue by apachemycat** [Facico/Chinese-Vicuna#179]
class prompt:
    def __init__(self, tokenizer, max_len, add_eos=True):
        self.tokenizer = tokenizer
        self.max_len = max_len
        self.add_eos=add_eos

class instruct_prompt(prompt):
    prompt = (
        **"Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n"**
        "### Instruction:\n{instruction}\n\n### Response:"
    )
    prompt_input = (
        **"Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n"**
        "### Instruction:{instruction}\n\n### Input:{input}\n\n### Response:"
    )

个人感觉，这些英文的部分是多余的，其他训练的代码中，没有见到类似的内容？

**Comment by Facico** [comment]
不是多余的，这些内容非常必要，不管是哪个和instruction tuning有关的代码基本都有这些东西
