### ISSUE TITLE
请问从哪里下载你们最新的模型，之前的checkpoint链接404了

### ISSUE THREAD

**Issue by Lufffya** [Facico/Chinese-Vicuna#182]

**Comment by jingtian11** [comment]
对没有checkpoint了，应该怎么做啊

**Comment by jingtian11** [comment]
请问问题解决了嘛

**Comment by Facico** [comment]
我们把模型都放到huggingface上了，https://huggingface.co/Chinese-Vicuna，原来的checkpoint-11600对应https://huggingface.co/Chinese-Vicuna/Chinese-Vicuna-lora-7b-belle-and-guanaco-11600。checkpoint-final对应https://huggingface.co/Chinese-Vicuna/Chinese-Vicuna-lora-7b-belle-and-guanaco。

我之后把文档更新一下
