### ISSUE TITLE
关于数据集的准备和处理

### ISSUE THREAD

**Issue by kostya-sec** [Facico/Chinese-Vicuna#187]
您好。我想尝试微调关于剧本的Lora。我看到指令精调使用数据模板是
{
"instruction": "",
"input": "",
"output": ""
}
我的原始数据类似下面这种：
一些环境描述和背景描述。
旁白：旁白说的话1.
角色1：角色1的话1. （角色情绪和动作）
角色2：角色2的话1. （角色情绪和动作）
xxxx

如果是这样的话，想请教一下应该怎么样处理源数据到模板数据会比较合适。非常感谢

**Comment by Facico** [comment]
参考[这里](https://huggingface.co/datasets/Chinese-Vicuna/instruct_chat_50k.jsonl)把任务描述清楚就好。
或者参照一下这个issue：#152
