### ISSUE TITLE
关于 finetune_others_continue.sh 的参数问题

### ISSUE THREAD

**Issue by Lufffya** [Facico/Chinese-Vicuna#200]
我注意到 finetune_others_continue 脚本里面有一个 `--lora_remote_checkpoint $lora_remote_checkpoint ` 的参数

1，这个参数有什么作用？
2，和 `--resume_from_checkpoint $lora_checkpoint ` 有什么区别？

最后我参考了 [Chinese-Vicuna-medical](https://github.com/Facico/Chinese-Vicuna/blob/master/docs/performance-medical.md) 没有使用 `--lora_remote_checkpoint `

**Comment by FURYFOR** [comment]
`--lora_remote_checkpoint` 是huggingface上远程checkpoint,`--resume_from_checkpoint`是加载本地checkpoint，应该是二者选其一，若使用本地checkpoint可在finetune_others_continue.sh删除`--lora_remote_checkpoint $lora_remote_checkpoint`

**Comment by FURYFOR** [comment]
`--lora_remote_checkpoint` 是huggingface上远程checkpoint,`--resume_from_checkpoint`是加载本地checkpoint，应该是二者选其一，若使用本地checkpoint可在finetune_others_continue.sh删除`--lora_remote_checkpoint $lora_remote_checkpoint`
