### ISSUE TITLE
拉去最新分支之后，通过pip install安装好了bitsandbytes==0.37.2，但是通过finetune_other_continue执行的时候，报此模块没有__version__

### ISSUE THREAD

**Issue by summer-silence** [Facico/Chinese-Vicuna#219]
# if USE_8bit is True:
#     assert bnb.__version__ >= '0.37.2', "Please downgrade bitsandbytes's version, for example: pip install bitsandbytes==0.37.2"
注意到新的代码中，对原先的finetune_other_continue做出了修正，添加了assert判断，然而执行的时候显示bnb没有__version__。
目前是采用的将此两行进行注释的方式，这种方式可以正常运行.
![image](https://github.com/Facico/Chinese-Vicuna/assets/57739107/a64e5f0c-5da9-416d-ba84-3e380bd0a606)

**Comment by smartswordsman** [comment]
你好，请问这个问题怎么解决的呢？

**Comment by kbwzy** [comment]
同最新代码：
我是直接注释掉，这两行代码：
![image](https://github.com/Facico/Chinese-Vicuna/assets/12123683/dbcc8412-cbe8-48f7-87ef-3b7c317dfc99)
看起来是可以跑得，但是会报另外一个错误。
![image](https://github.com/Facico/Chinese-Vicuna/assets/12123683/a4750129-b52a-4749-af2a-45be493eb0e1)

![image](https://github.com/Facico/Chinese-Vicuna/assets/12123683/17f41f86-a46e-4624-8026-7fe3bdec0e3b)

**Comment by kbwzy** [comment]
pip uninstall nvidia-cublas-cu11之后就好了

> 

pip uninstall nvidia-cublas-cu11之后就好了

**Comment by kbwzy** [comment]
> 同最新代码： 我是直接注释掉，这两行代码： ![image](https://user-images.githubusercontent.com/12123683/245439186-dbcc8412-cbe8-48f7-87ef-3b7c317dfc99.png) 看起来是可以跑得，但是会报另外一个错误。 ![image](https://user-images.githubusercontent.com/12123683/245439887-a4750129-b52a-4749-af2a-45be493eb0e1.png)
> 
> ![image](https://user-images.githubusercontent.com/12123683/245439755-17f41f86-a46e-4624-8026-7fe3bdec0e3b.png)
是这个包引起的。

pip uninstall nvidia-cublas-cu11之后就好了

**Comment by Facico** [comment]
感谢提醒，这行代码没测过，只是想提醒训练8bit的时候bitsandbytes的版本问题，我现在改成warning了
没想到bitsandbytes没写__version__这个属性。。。

**Comment by summer-silence** [comment]
@Facico 那我关闭问题了
