### ISSUE TITLE
量化后的模型4bit，模型输出是乱码

### ISSUE THREAD

**Issue by GUORUIWANG** [Facico/Chinese-Vicuna#23]
用的llama_quant.py，未用数据集评估，量化后模型输出是乱码，请问啥原因呀

**Comment by Chuge0335** [comment]
> 用的llama_quant.py，未用数据集评估，量化后模型输出是乱码，请问啥原因呀

方便提供输出的跟多细节吗？

**Comment by GUORUIWANG** [comment]
> > 用的llama_quant.py，未用数据集评估，量化后模型输出是乱码，请问啥原因呀
> 
> 方便提供更多输出细节吗？

输入不一样，输出都是乱码
![image](https://user-images.githubusercontent.com/42712819/230251586-467bec12-d7c2-4872-89b0-66832e87a9e5.png)

**Comment by Chuge0335** [comment]
量化工具已经更新，效果请查看:https://github.com/Facico/Chinese-Vicuna/blob/master/tools/readme_zh.md
