### ISSUE TITLE
你好，请问上下文对话中你们是引入了langchain吗？

### ISSUE THREAD

**Issue by haxx12113** [Facico/Chinese-Vicuna#25]
请问下上下文理解这里使用了https://github.com/deep-diver/Alpaca-LoRA-Serve
https://github.com/Facico/Chinese-Vicuna/blob/master/docs/performance.md
还是langchain？
我没太理解，langchain和Alpaca-LoRA-Serve中多轮对话的区别，希望得到解答，谢谢！

**Comment by Facico** [comment]
@haxx12113 
 Alpaca-lora-serve只是一个webui的服务，我们当初因为它可以支持流式输出才引入了一下，但因为他不支持beam search的情况所以不太好使，你可以忽略这个配置。我们自己开发的generate.py和chat.py是都是可以支持流式输出，同时还能支持beam search和Repetition Penalty的。（chat.py目前效果还有点差，可以直接用我们的interaction.py来进行对话）

我们上下文理解就是将历史对话拼接在一起作为一个场景，再进行新的对话。langchain暂时我们还没有引入。

**Comment by haxx12113** [comment]
谢谢解答，你们拼接做法和langchain每次对话都拼接的实现应该一样的
