### ISSUE TITLE
可以更新一下requirements吗？

### ISSUE THREAD

**Issue by estuday** [Facico/Chinese-Vicuna#257]
您好，项目中很多代码在提供的环境中跑不起来了，可以更新一下requirements吗？

**Comment by Facico** [comment]
@estuday 可能因为安装python时其他默认的环境会升级，导致pydantic、datasets之类的包版本不对。刚刚更新了一下，peft、bitsandbyte这些库之前的bug官方都修好了，基本上都可以用最新的版本。
