### ISSUE TITLE
关于语料问题

### ISSUE THREAD

**Issue by ZenXir** [Facico/Chinese-Vicuna#26]
从网盘新下载了 merge.json 语料
发现原来是 663M 现在变成389M了
是什么原因语料变小 只保留了70W+条 大佬？

**Comment by Facico** [comment]
@ZenXir  改成utf-8格式了

**Comment by Facico** [comment]
ascii格式表示长度要长

**Comment by ZenXir** [comment]
确实 刚看了下我之前转成utf8格式的 确实也是389M 哈哈
