### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers.deepspeed'

### ISSUE THREAD

**Issue by ljy-do** [Facico/Chinese-Vicuna#260]
在提问之前，请务必先看看这个[注意事项!!!](https://github.com/Facico/Chinese-Vicuna/blob/master/docs/notes.md)

如果你遇到问题需要我们帮助，你可以从以下角度描述你的信息，以便于我们可以理解或者复现你的错误（学会如何提问不仅是能帮助我们理解你，也是一个自查的过程）：
1、你使用了哪个脚本、使用的什么命令
2、你的参数是什么（脚本参数、命令参数）
3、你是否修改过我们的代码
4、你用的哪个数据集

如果上面都是**保持原样**的，你可以描述“我用的哪个脚本、命令，跑了哪个任务，然后其他参数、数据都和你们一致”，便于我们平行地理解你们的问题。

然后你可以从环境的角度描述你的问题，这些问题我们在readme已经[相关的问题及解决](https://github.com/Facico/Chinese-Vicuna/blob/master/docs/notes.md)可能会有描述：
1、哪个操作系统
2、使用的什么显卡、多少张
3、python的版本
4、python各种库的版本

然后你也可以从运行的角度来描述你的问题：
1、报错信息是什么，是哪个代码的报错（可以将完整的报错信息都发给我们）
2、GPU、CPU是否工作正常

同时你也可以看看issue，或者我们整理的信息里面有没有类似的问题[相关的问题及解决](https://github.com/Facico/Chinese-Vicuna/blob/master/docs/notes.md)

当然这只是个提问说明，你没有必要一一按照里面的内容来提问。

**Comment by Facico** [comment]
transformers版本太新了？最新的用法是from transformers.integrations import deepspeed这样的。
不过按照requirement里固定版本的transformers应该没这个问题？

**Comment by ljy-do** [comment]
所以要下载你固定的版本哇？我当时是直接git clone transformers的官网然后本地上传到服务器的sitepackages里面

**Comment by ljy-do** [comment]
> transformers版本太新了？最新的用法是from transformers.integrations import deepspeed这样的。 不过按照requirement里固定版本的transformers应该没这个问题？

所以要下载你固定的版本哇？我当时是直接git clone transformers的官网然后本地上传到服务器的sitepackages里面

**Comment by Facico** [comment]
复现肯定都是要根据仓库的指南/环境安装的，开源依赖迭代的太快了，很多写法过几个周就变一次

**Comment by ljy-do** [comment]
> 复现肯定都是要根据仓库的指南/环境安装的，开源依赖迭代的太快了，很多写法过几个周就变一次

你好但是服务器不能连外网qwq，能告诉我把这个版本先下载到本地的指令吗

**Comment by Facico** [comment]
https://github.com/huggingface/transformers/tree/0dcb46e7a4a9e587ba84ff35778ab4233a184c11
