### ISSUE TITLE
https://chat.lmsys.org/ 問到第三輪會跑超久

### ISSUE THREAD

**Issue by iamblue** [Facico/Chinese-Vicuna#28]
https://chat.lmsys.org/ 這個同一個對話框問答到第三輪時，似乎時間就會跑超久或無反應？請問這是什麼原因？

**Comment by Facico** [comment]
@iamblue 這個網站不是我們開發的，不過在對輪對話的時間越來越長可能是拼接的東西（歷史對話）越來越長的原因，我們自己開發的多輪對話為了保證硬件上的效率會可以選擇截斷一定的歷史信息（max memory）
