### ISSUE TITLE
Vicuna.cpp 衍生自  Llama.cpp 还是 Alpaca.cpp？  基于 Alpaca 和 Llama 中文embedding后  finetune出来的模型会通用吗？

### ISSUE THREAD

**Issue by ZenXir** [Facico/Chinese-Vicuna#33]
[Vicuna.cpp](https://github.com/Facico/Chinese-Vicuna/tree/master/tools/Vicuna.cpp)

Vicuna.cpp 衍生自  Llama.cpp 还是 Alpaca.cpp？  
基于 Alpaca 和 Llama 中文embedding后  finetune出来的模型会通用吗？

**Comment by LZY-the-boys** [comment]
参考了Alpaca.cpp。模型是否通用和在finetune的时候的prompt有关，如果使用了和llama/alpaca一样的prompt，理论上是通用的。中文embedding因为替换了token的含义，对直接使用不同embedding训练出来的lora可能是有影响的，因为目前还没人公开基于llama的中文embedding，所以我们也无从验证

**Comment by LZY-the-boys** [comment]
见finetune.py里边的`generate_prompt`:

```
f"""Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
{data_point["instruction"]}

### Response:
{data_point["output"]}"""
```

**Comment by ZenXir** [comment]
是的 看了这个 基本都差不多
你说的差异 具体是什么大佬？

**Comment by LZY-the-boys** [comment]
就是你如果训练用的不同的prompt，然后在生成的时候还是用的默认的prompt，效果就不一样了
