### ISSUE TITLE
关于继续训练（continue finetuning）

### ISSUE THREAD

**Issue by creamiracle** [Facico/Chinese-Vicuna#38]
你好，感谢分享。
是否可以理解为，在垂类应用上，构造好预料，替换sh中的data_path，然后运行sh文件就能在你们分享的模型权重下继续进行训练，以得到一个应用于上述垂类语料中的模型呢？
谢谢

**Comment by Facico** [comment]
你可以参考我们在医学问答的案例[medical](https://github.com/Facico/Chinese-Vicuna/blob/master/docs/performance-medical.md)

**Comment by creamiracle** [comment]
> 1、这个是用于生成的参数，在generate那些推理脚本那种有 2、因为你要用新的数据，不能跳过他们 3、这里的逻辑是拼接，就是把20w的数据重复拼接3.5次

好的谢谢，前面我都理解了，第三个的意思是先复制20w成为70w然后再继续训练么？那为什么不能在20w上只训练一个epoch呢？

**Comment by Facico** [comment]
1、不是先复制成20w（因为我们医疗问答的规模就是20w），是直接复制成70w
2、因为我们提供的优化器参数是一轮70w的，所以是直接在这个规模上提供的continue_finetune

**Comment by creamiracle** [comment]
> 

您好，我理解了，那如果我按照您的方式继续训练，也需要变成70w的数据，是这个意思吧？
2中这个参数是在哪里定义的呢？Finetuning中的trainerArguments么？
thx

**Comment by Facico** [comment]
是的，如果不到70w会自动重复拼接到70w（并没有显式的拼接，而是重复了70w训练的step）
优化器参数和训练策略参数就是那几个optimizer.pt、scheduler.pt、scaler.pt等

**Comment by creamiracle** [comment]
> 是的，如果不到70w会自动重复拼接到70w（并没有显式的拼接，而是重复了70w训练的step） 优化器参数和训练策略参数就是那几个optimizer.pt、scheduler.pt、scaler.pt等

这个**自动重复拼接到70w**的原理是什么呢，我对这部分不是很熟悉？烦请您解答一下，谢谢。

**Comment by Facico** [comment]
就是重复训练这段数据，相当于在时间上拼接

**Comment by creamiracle** [comment]
> 就是重复训练这段数据，相当于在时间上拼接

那就是说如果直接用这20w数据继续训练，不去复制，应该也不会报错吧

**Comment by Facico** [comment]
是的
