### ISSUE TITLE
V100显卡，完全follow说明跑的finetue，会出现乱码。 似乎是8bit的原因。

### ISSUE THREAD

**Issue by jzsbioinfo** [Facico/Chinese-Vicuna#44]
![image](https://user-images.githubusercontent.com/38813875/230564865-07327d0c-6e15-4dd0-b6fb-3b38123565cf.png)

**Comment by Facico** [comment]
应该是v100在8bit，同时也可以检查一下相关依赖的
版本的问题。
类似问题见[该issue](https://github.com/Facico/Chinese-Vicuna/issues/39)

可以试着不开8bit，只使用fp16

**Comment by jzsbioinfo** [comment]
难道v100对int8的模型不适配？有没有说具体原因，能给个链接？

**Comment by Facico** [comment]
我上面给你贴的那个issue链接里面有写
