### ISSUE TITLE
generate_quant.py 脚本运行失败

### ISSUE THREAD

**Issue by greatewei** [Facico/Chinese-Vicuna#46]
我想要运行一个量化模型，出现错误：ModuleNotFoundError: No module named 'gptq'

generate_quant.py 不能正常运行，是不是少了某些文件？

**Comment by Facico** [comment]
@greatewei 可以参考我们的[tool readme](https://github.com/Facico/Chinese-Vicuna/issues/39)，里面介绍了如何使用gptq量化运行

**Comment by greatewei** [comment]
> @greatewei 可以参考我们的[tool readme](https://github.com/Facico/Chinese-Vicuna/blob/master/tools/readme_zh.md#quantize-llama)，里面介绍了如何使用gptq量化运行

嗯，我成功训练了量化模型，但是在第三步执行 generate_quant.py文件发生了错误，缺少了gptq模块

**Comment by Facico** [comment]
我们在tool readme中Quantize LLaMA第二行，第二句话“运行下面的代码前，你需要用 pip install gptq>=0.0.2 命令来安装 gptq。”讲了如何安装gptq

**Comment by greatewei** [comment]
> 我们在tool readme中Quantize LLaMA第二行，第二句话“运行下面的代码前，你需要用 pip install gptq>=0.0.2 命令来安装 gptq。”讲了如何安装gptq

看到了，感谢！

**Comment by greatewei** [comment]
@Facico 你好，我遇到了一个问题，generate_quant.py脚本执行量化脚本后，效果很差，如图：
![image](https://user-images.githubusercontent.com/40682309/233331730-a6bd1985-0d51-4744-96f8-18abed5763da.png)
我的量化过程如下：
1.  13b-lora 与 llama13b进行合并生成一个新的模型 chinese-v-13b-hf， 这个模型测试过，能够正常的交流。
2. 执行命令 ```python tools/llama_quant.py /data/chat/models/chinese-v-13b-hf ptb  --wbits 4 --groupsize 128 --save /data/chat/models/chinese-v-13b-hf/pyllama-4b.pt``` 进行了模型量化，最终输出了 pyllama-4b.pt文件
3. 执行命令```python tools/generate_quant.py  --model_path "/data/chat/models/chinese-v-13b-hf" --quant_path "/data/chat/models/chinese-v-13b-hf/pyllama-4b.pt"  --wbits 4``` 

是不是哪个环节出了错误
