### ISSUE TITLE
 无法成功执行generate.sh以及interaction.sh

### ISSUE THREAD

**Issue by alisyzhu** [Facico/Chinese-Vicuna#55]
完成fine-tune后，按照readme里配置好脚本参数后，执行predict报错，烦请帮忙看看是哪里配置没有修改吗？
1、sh generate.sh
<img width="773" alt="image" src="https://user-images.githubusercontent.com/127492258/230855832-dea235dd-b977-4ebd-a937-d0d7f5a5e16c.png">
debug后发现，在GPU加载完LLAMA模型后，执行
<img width="784" alt="image" src="https://user-images.githubusercontent.com/127492258/230856069-023311a3-e7e5-40fc-a4cd-6126b19a434f.png">
后model=None了。。
2、sh interaction.sh
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/127492258/230856215-21b32751-2990-47ef-ac8d-11b4c7f68cb4.png">
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/127492258/230856263-723d7482-2c77-4d3c-a2c7-76126365e2df.png">

**Comment by alisyzhu** [comment]
大概知道是什么问题了 ~

**Comment by Facico** [comment]
抱歉这么回复，这个问题是peft版本的问题，可以参考这个[issue](https://github.com/Facico/Chinese-Vicuna/issues/51)
