### ISSUE TITLE
peft版本问题

### ISSUE THREAD

**Issue by cc-doughnut** [Facico/Chinese-Vicuna#58]
开始头铁用的最新版的peft仓库在运行generate,py会出现model.peft config字典不存在peft type的问题
报错位置在utils里面715行：
            model = dispatch_model(model, device_map=device_map)
            hook = AlignDevicesHook(io_same_device=True)
            if model.peft_config.peft_type == PeftType.LORA:
                add_hook_to_module(model.base_model.model, hook)
            else:
                remove_hook_from_submodules(model.prompt_encoder)
                add_hook_to_module(model.base_model, hook)
把peft仓库降级到requirements里面版本不会报错
最终没找到原因 先报个问题吧 盼复 谢谢!

**Comment by Facico** [comment]
peft这个仓库还在开发阶段，更新的比较快，建议还是固定用一个版本
