### ISSUE TITLE
生成语料相关

### ISSUE THREAD

**Issue by ZenXir** [Facico/Chinese-Vicuna#6]
大佬老师，看到有用到https://github.com/LianjiaTech/BELLE
生成的语料
刚看了下这个工程
有两点不明白，麻烦大佬老师帮解释下吧：
1、为什么需要种子任务 zh_seed_tasks.json？
	种子任务的作用是什么？

2、生成数据时
```
　　pip install -r requirements.txt
	export OPENAI_API_KEY=YOUR_API_KEY
	python generate_instruction.py generate_instruction_following_data
```

最后的这个参数 generate_instruction_following_data 是什么大佬老师？ 是表示生成数据的存储文件吗？
非常感谢大佬老师

**Comment by Facico** [comment]
别的仓库的问题你去问别的大佬老师吧。。。

**Comment by ZenXir** [comment]
好的

**Comment by ZenXir** [comment]
种子的作用主要是利用in context learning的方法，让chatgpt生成更多的指令数据
generate_instruction_following_data是里面生产数据的函数。
