### ISSUE TITLE
How to alter local url address,thx

### ISSUE THREAD

**Issue by Modas-Li** [Facico/Chinese-Vicuna#61]
Running on local URL:  http://127.0.0.1:7860
Want to change it to 0.0.0.0:7860

**Comment by Facico** [comment]
Add the parameter "server_name=0.0.0.0" to the "launch" at the bottom of the corresponding web visualization python program(such as generate.py)
for example
```
import gradio as gr

def main():
    gr.Interface(
            fn=lambda x: x,
        inputs=[
            gr.inputs.Textbox(lines=2, placeholder="Enter your question here:"),
        ],
        outputs=[gr.outputs.Textbox()],
    ).launch(server_name='0.0.0.0')

if __name__ == '__main__':
    main()
```
More settings can be found in this [project](https://github.com/gradio-app/gradio)
