### ISSUE TITLE
params.json cannot be found in downloaded huggingface 3epoch model path

### ISSUE THREAD

**Issue by Modas-Li** [Facico/Chinese-Vicuna#63]
Traceback (most recent call last):
  File "/data/Chinese-Vicuna/tools/convert_pth_to_ggml.py", line 64, in <module>
    with open(fname_hparams, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/Chinese-Vicuna/from/Chinese-Vicuna-lora-7b-3epoch-belle-and-guanaco/params.json'

If you encounter a problem and need our help, you can describe your information from the following perspectives so that we can understand or reproduce your error (learning how to ask questions is not only a way to help us understand you, but also a process of self-examination):
1, which script you used, what command you used
2, what are your parameters (script parameters, command parameters)
3, whether you have modified our code
4, which data set you used

If all of the above is **keep it as is**, you can describe "which script or command I used, which task I performed, and then the other parameters and data are the same as yours", so that we can understand your problem in a parallel way.

Then you can describe your problem from the perspective of the environment, which we have already [related problems and solutions](https://github.com/Facico/Chinese-Vicuna/blob/master/docs/problems.md) in the readme may describe:
1, which operating system
2, what graphics card is used, how many
3, the version of python
4, the version of various python libraries

Then you can also describe your problem from a running point of view: 1:
1, what is the error message, which code is the error message (you can send us all the complete error message)
2. whether the GPU and CPU are working properly

At the same time you can also look at the issue, or we organize the information whether there are similar problems [related problems and solutions](https://github.com/Facico/Chinese-Vicuna/blob/master/docs/problems.md)

This is only a question description, you do not have to follow the contents of the questions.

**Comment by Facico** [comment]
Did you run this script（bash prepare_llama_cpp.sh）?
You can check the parameters in the script prepare_llama_cpp.sh and set them to be exact. In the script, the python code merge_lora.py will be run and it will generate the corresponding params.json

**Comment by Modas-Li** [comment]
> Did you run this script（bash prepare_llama_cpp.sh）?
> 
> You can check the parameters in the script prepare_llama_cpp.sh and set them to be exact. In the script, the python code merge_lora.py will be run and it will generate the corresponding params.json

but tracelog says it cannot find the file params.json
