### ISSUE TITLE
数据集无法下载

### ISSUE THREAD

**Issue by Pyjacc** [Facico/Chinese-Vicuna#67]
你好，以下数据集无法下载，https://drive.google.com/file/d/1tzXVhS74m-EtoFot7hEc005LDeZGPit_/view?usp=sharing
![image](https://user-images.githubusercontent.com/47920481/231380016-839fa082-ed0c-49b0-9b17-ce9d197aa2b7.png)
可以将该数据集放到网盘或者其他可以下载的位置么，谢谢！

**Comment by Facico** [comment]
这三个都是同一个数据
