### ISSUE TITLE
新手小白在线求入门

### ISSUE THREAD

**Issue by ws1957** [Facico/Chinese-Vicuna#69]
我是一个新手，这是我在gitbub上下载的第一个项目，无GPU，找不到node_modules的文件和dist文件夹，求大佬带路

**Comment by Facico** [comment]
我们的程序除了c++推理部分基本都是基于python写的，你说的东西应该是和前端有关的。我们的前端是用gradio写的，如果你想了解相关的文件可以参考[gradio这个项目](https://github.com/gradio-app/gradio/blob/9840e87e829062246808fc130dd05b4b2176ee7f/website/homepage/.gitignore)，一般这两个东西是不会上传的。
