### ISSUE TITLE
generate: AttributeError: 'NoneType' object has no attribute 'eval'

### ISSUE THREAD

**Issue by Tian14267** [Facico/Chinese-Vicuna#70]
我在运行 `generate.sh`的时候，提示报错：
```
Traceback (most recent call last):
  File "generate.py", line 110, in <module>
    model.eval()
AttributeError: 'NoneType' object has no attribute 'eval'

```
我检查了代码，问题出在这里：
![image](https://user-images.githubusercontent.com/27938135/231686983-7bfa246a-94cd-4d8c-8156-7c71cacff392.png)
当把这些注释之后，就可以了。但是却无法使用 `stream_generate`。请问这是啥情况

**Comment by xqmmy** [comment]
peft版本的问题

**Comment by yanxp** [comment]
@xqmmy @Tian14267 这个问题解决了嘛 遇到类似的问题，peft用哪个版本呢，用的是推荐版本

**Comment by xqmmy** [comment]
> @xqmmy @Tian14267 这个问题解决了嘛 遇到类似的问题，peft用哪个版本呢，用的是推荐版本

#51 看下这个

**Comment by Facico** [comment]
@yanxp 
我们在最新的requirement.txt中的固定的某个commit hash的版本应该是没有问题的`git+https://github.com/huggingface/peft@e536616888d51b453ed354a6f1e243fecb02ea08`

**Comment by mrbemani** [comment]
用了最新的版本PEFT还是同样的错误。

```bash
(textgen) [shiqi@nqs-server Chinese-Vicuna]$ ./generate.sh 
bin /home/shiqi/anaconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
Namespace(model_path='decapoda-research/llama-7b-hf', lora_path='Chinese-Vicuna/Chinese-Vicuna-lora-7b-belle-and-guanaco', use_typewriter=0, use_local=0)
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'LLaMATokenizer'. 
The class this function is called from is 'LlamaTokenizer'.
Chinese-Vicuna/Chinese-Vicuna-lora-7b-belle-and-guanaco/adapter_model.bin
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████| 33/33 [00:12<00:00,  2.68it/s]Traceback (most recent call last):
  File "/mnt/d/tools/nlp/Chinese-Vicuna/generate.py", line 110, in <module>
    model.eval()
AttributeError: 'NoneType' object has no attribute 'eval'
```

**Comment by Facico** [comment]
@mrbemani 但是不应该是最新版吧，这个问题就是因为PEFT一直在更新导致的问题。所以我们现在是固定了以前的一个版本。

**Comment by mrbemani** [comment]
> @mrbemani 但是不应该是最新版吧，这个问题就是因为PEFT一直在更新导致的问题。所以我们现在是固定了以前的一个版本。

是最新版的Chinese-Vicuna，标点符号忘记打了，哈哈

**Comment by Facico** [comment]
@mrbemani 那你可以把peft版本卸了重装一下
```
!pip uninstall peft
!pip install git+https://github.com/huggingface/peft@e536616888d51b453ed354a6f1e243fecb02ea08
```

**Comment by Tian14267** [comment]
@Facico @yanxp 换成 peft==0.2.0 就行了
![image](https://user-images.githubusercontent.com/27938135/232969082-9bb6a06e-f28c-47af-a913-4d181bf77ca0.png)

**Comment by summer-silence** [comment]
> @Facico @yanxp 换成 peft==0.2.0 就行了 ![image](https://user-images.githubusercontent.com/27938135/232969082-9bb6a06e-f28c-47af-a913-4d181bf77ca0.png)这个是有用的
