### ISSUE TITLE
无法安装git+https://github.com/huggingface/peft@e536616888d51b453ed354a6f1e243fecb02ea08

### ISSUE THREAD

**Issue by yeshcue** [Facico/Chinese-Vicuna#80]
使用pip  install git+https://github.com/huggingface/peft@e536616888d51b453ed354a6f1e243fecb02ea08
一直无法安装

**Comment by Facico** [comment]
报错信息是什么，我猜应该是网络的问题？

**Comment by BUPTccy** [comment]
> 报错信息是什么，我猜应该是网络的问题？

本身需要翻墙安装，若是服务器（机器）不方便翻墙，可以采取ssh方式，将公钥上传github后进行安装
也分享一下我自己研究出来的ssh链接形式（官方链接存在依赖问题）
git+ssh://git@github.com/huggingface/transformers.git
git+ssh://git@github.com/huggingface/peft.git
作者方便的话也可以作为另一种安装方式放在README中

**Comment by Adamlangc** [comment]
add https://ghproxy.com/
git+https://ghproxy.com/https://github.com/huggingface/peft@e536616888d51b453ed354a6f1e243fecb02ea08

**Comment by w179962443** [comment]
> > 报错信息是什么，我猜应该是网络的问题？
> 
> 本身需要翻墙安装，若是服务器（机器）不方便翻墙，可以采取ssh方式，将公钥上传github后进行安装 也分享一下我自己研究出来的ssh链接形式（官方链接存在依赖问题） git+ssh://[git@github.com](mailto:git@github.com)/huggingface/transformers.git git+ssh://[git@github.com](mailto:git@github.com)/huggingface/peft.git 作者方便的话也可以作为另一种安装方式放在README中

you got it，thks
