### ISSUE TITLE
想知道在推理的时候，Temperature、Beams Number 和 Repetiton Penalty等参数有什么意义，该怎么调整？

### ISSUE THREAD

**Issue by AIXiaoBaiDemon** [Facico/Chinese-Vicuna#86]

**Comment by Facico** [comment]
可以参考相关[资料](https://blog.csdn.net/muyao987/article/details/125917234)，网上相关资料可能更详细一点

**Comment by Albort-z** [comment]
@Facico 大佬有没有学习交流群？我看issues里好多都是询问和学习的

**Comment by Facico** [comment]
@Albort-z 是这样的，最近邮件都有点回不过来了，我建了一个qq群：532581765，可以在主页看到
