### ISSUE TITLE
Does it or will it support Vicuna-13b-v1.1 finetuning?

### ISSUE THREAD

**Issue by ghost** [Facico/Chinese-Vicuna#89]
Thanks for creating such an amazing project.

Vicuna-13b-v1.1 seems to achieve impressive performance in tasks in multiple languages. I believe it would be a good idea to conduct further fine-tuning based on it. So, will this project support Vicuna-13b-v1.1 finetuning later?

**Comment by qianchen94** [comment]
same question

**Comment by Facico** [comment]
I'm sorry, too much has happened recently to forget this issue. 
While Vicuna-13b-1.1 does work well, they do however require a lot of resources (they are fully parameter fine-tuned and do not use 8bit). Our project will still focus on training on low resources for now, and we will release the next version with better results as soon as possible.
